module.exports = [
    {
        id: "s1",
        text: "Nie dla wszystkich śmierć na wojnie okazuje się szybka. Żołnierz, którego mamy przed sobą, leży w niewielkim, zaśmieconym pomieszczeniu na porzuconych noszach. Jego mundur jest przepocony, chociaż wokół panuje zimno. Podchodzimy bliżej. Mężczyzna krztusi się własną krwią, jedną ręką dociskając prowizoryczny opatrunek. Wie, że jego chwile są policzone, ale nie ma odwagi i sił, by sam ze sobą skończyć. Drżącą dłonią podaje nam nóż i prosi, abyśmy przynieśli mu ulgę.",
        rule: "",
        show1: true,
        transText1: "Spełnijmy jego prośbę - WYBIERZ 1 Z OBECNYCH TU POSTACI ",
        changeTo1: 88,
        show2: true,
        transText2: "Spróbujmy mu pomóc. Może coś da się jeszcze zrobić",
        changeTo2: 56,
        show3: true,
        transText3: "Zostawmy go. Nie możemy mu pomóc ani nie chcemy mieć jego krwi na rękach",
        changeTo3: 27,
        reset: ""
    },
    {
        id: "s2",
        text: "Ta część kanałów wydaje się starsza od reszty. Idziemy niemal po omacku, opierając się rękoma o kamienne ściany. Wąski chodnik prowadzi wzdłuż szerokiego zbiornika ścieków. Kamień jest tu zmurszały i osuwa się spod stóp. \"Plum!\" Mija chwila, nim słyszymy odgłos uderzenia kawałka cegły o lustro zmętniałej wody. Jeden nieostrożny ruch i my też spadniemy w dół.",
        rule: "",
        show1: true,
        transText1: "Spróbujmy przejść",
        changeTo1: 62,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Ta droga jest zbyt niebezpieczna, lepiej kończmy na dziś i wracajmy do schronienia - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY"
    },
    {
        id: "s3",
        text: "Przemycanie papierosów przez oblężone miasto to dla Bobana chleb powszedni. Mężczyzna trafił na nas w ciemnym kanale. Ma zniszczoną nałogiem twarz i krótko ścięte włosy. Szczerbaty uśmiech nie należy do sympatycznych i podobno jest efektem jakiejś nieuczciwej transakcji. Wypchane papierosami kieszenie często powodują problemy, ale Boban nie zna innego życia. Wszędzie nosi ze sobą broń, święcie wierząc, że jeśli sprawy nie rozwiąże \"fajka pokoju\", to zawsze pozostaje niezawodna kula. \"W czasie wojny szmuglowałem, no to co miałbym w czasie wojny robić? Macie szczęście, że wam generał wszystkich faj nie wykupił. Ja mam najlepsze w mieście, no i taniej się nie da\" - mówi z dumą, prezentując resztki swojego towaru.",
        rule: "Możemy kupić od niego paczkę papierosów (patrz Dziennik: HANDEL) za żetony o wartości 5. Prowizja: 0. PACZKA PAPIEROSÓW: Zapisz \"Paczka Papierosów, s3, I I I\" na Pustym żetonie i połóż go na Stosie Znalezisk. Traktuj go jak zielony żeton o wartości 6 za każdą kreskę i wadze 0. W dowolnym momencie możesz skreślić 1 kreskę, aby dodać 6 żetonów Papierosów. Gdy skreślisz ostatnią kreskę, usuń ten żeton z gry.",
        show1: true,
        transText1: "Jeśli kupiliśmy paczkę papierosów",
        changeTo1: 68,
        show2: true,
        transText2: "Jeśli nie",
        changeTo2: 86,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s4",
        text: "Echa głosów niosą się po sklepieniach kanału na moment przed tym, jak dostrzegamy ludzkie cienie. Ton głosu już z dala sugeruje kłótnię. Chwilę później zaczynamy rozpoznawać poszczególne słowa: \"Mówiliście, że to blisko, a idziemy już godzinę\" - skarży się niska postać. Po cieniu na ścianie orientujemy się, że nieznajomy energicznie gestykuluje, jakby rozważał, czy nie przebiec w przeciwną stronę. \"Trzeba było naokoło, ale teraz do wyjścia z miasta niedaleko, pan zobaczy\" - zgarbiony czarny kontur pojawia się w mdłym świetle latarki trzeciej postaci. \"Oby! Pamiętajcie ile wam zapłaciłem. Dam drugie tyle, jeśli wyprowadzicie mnie stąd żywego\" - odpowiada mikrus. \"Zaraz zobaczymy, czy aż tyle masz. Andrej, kończmy z nim!\" - odzywa się trzeci głos. Jego cień rośnie nagle i zupełnie zakrywa dwie pozostałe postacie. Słyszymy rwany krzyk.",
        rule: "",
        show1: true,
        transText1: "Biegniemy na pomoc ofierze",
        changeTo1: 53,
        show2: true,
        transText2: "Lepiej nie kusić losu",
        changeTo2: 78,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s5",
        text: "Dwa kartony książek - tylko tyle i aż tyle udało mu się uratować i zabrać do kanału. Mężczyzna, którego mamy przed sobą, ma poparzone, grube dłonie. Był ochroniarzem w bibliotece. Gdy spadły bomby i ogień pochłaniał budynek, zaczął wynosić z zaplecza wszystko, co wpadło mu w rękę. \"I na co mi to wszystko? Przecież teraz nikt tego nie będzie czytał. Było iść do żony, gdy zaczęło się bombardowanie, może bym zdążył chociaż do małej, nim umarła. Może, gdybym mógł cofnąć czas...\" Przyglądamy się budzącej żal postaci, która wolała ratować książki niż własną rodzinę.",
        rule: "",
        show1: true,
        transText1: "\"Czasu nie cofniemy, ale może te książki będą miały wartość dla potomnych. Mógłbyś przenieść je w bezpieczne miejsce\"",
        changeTo1: 65,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zostawmy go z jego zmartwieniami. To nie nasz problem - WRÓĆ DO GRY"
    },
    {
        id: "s6",
        text: "Od dłuższego czasu czujemy się obserwowani. W szparach między cegłami dostrzegamy zarys niskiej postaci. Wygląda na to, że ktoś podąża naszym śladem, korzystając z równoległego korytarza. Wyraźnie słyszymy towarzyszące nam kroki - powolne i ciche. Ktokolwiek za nami idzie, nie zamierza się ujawnić",
        rule: "",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 60,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s7",
        text: "W środkowej części kanałów natrafiamy na zamaskowany gruzami kabel telefoniczny. W zamierzeniu miał łączyć dowództwo garnizonu w śródmieściu z ogniskami oporu za rzeką. Nie udało się. Połączenie zostało wedle plotek przerwane przez sabotażystę, którego ciało być może mamy właśnie przez sobą. Do mężczyzny strzelano kilkakrotnie z bliska, zupełnie jak do tarczy treningowej. Dookoła ciał jest jednak więcej. Zaścielają cały korytarz. Mundury łącznościowców, sanitariuszy, żołnierzy. Mundury obu stron, wszyscy tak samo martwi, ograbieni ze wszystkiego, co miało jakąkolwiek wartość. Przechodzimy obok nieruchomych zwłok i zamykamy im otwarte oczy. Przynajmniej tyle możemy zrobić - zdobyć się na ostatni ludzki gest.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s8",
        text: "W wąskim przejściu udaje nam się wypatrzyć jakiś ruch. Mężczyzna ubrany w wełniany płaszcz zaklinował się w ciasnym tunelu. Chciał przepchnąć się przez szczelinę z całym plecakiem i niewiele brakowało, aby ten pomysł okupił życiem. Wspólnymi siłami wyswabadzamy mężczyznę z pułapki. Jego podziękowaniom nie ma końca. Dzieli się z nami wyjętym z plecaka chlebem i opowiada, że wraz z bratem, Petarem, ledwie uratował się z pogromu swojej rodzinnej wsi. Obaj próbowali przedrzeć się do miasta przez kanały. Jego brat musiał gdzieś zabłądzić, ale chłopak nie traci nadziei, że uda mu się go odszukać. Instruujemy go, jak przebyć drogę, którą sami tu dotarliśmy, by wydostać się do bezpieczniejszej części miasta. Po chwili po mężczyźnie pozostało już tylko wspomnienie. Ruszamy dalej.",
        rule: "Obniż Głód 1 z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s9",
        text: "Ciemny, śmierdzący tunel kończy się zawaloną ścian, przez którą bez trudu przedostajemy się do niewielkiego pomieszczenia. Oprócz śmieci leży tu kilka zawilgoconych książek i pokryte kurzem figurki świętych. Nie jesteśmy tu jednak sami. Troje zmarźniętych dzieci tuli się do siebie w kącie pokoju. Patrzą na nas jak na potwory, a przerażenie w ich oczach jest nieopisywalne. Nie odpowiadają na żadne pytanie, zupełnie tak, jakby nie rozumiały ani jednego naszego słowa. Co z nimi zrobić?",
        rule: "",
        show1: true,
        transText1: "Ruszajmy dalej. Nie uratujemy wszystkich sierot, choćbyśmy chcieli",
        changeTo1: 84,
        show2: true,
        transText2: "Spróbujmy przekonać dzieci, by ruszyły z nami do wyjścia. Może ktoś na zawnątrz się nimi zaopiekuje",
        changeTo2: 97,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s10",
        text: "Kolektor ma szerokość zaledwie metra, ale o dziwo jest suchy. Czołgamy się uważając, by nie zablokować się w ciasnym przejściu. Droga przed nami zakręca i nagle zaczyna opadać. Przedtem był to najwyraźniej tunel regulujący poziom ścieków, teraz są to raczej śliskie schody z nadzwyczaj niskim stropem. Powoli schodzimy w dół, modląc się, aby tunel nie okazał się ślepą odnogą. Ciche modlitwy tym razem zostają wysłuchane. Udaje nam się bez szwanku pokonać wąski wylot na dole... ale przeciskając się wąskim przejściem uszkadzamy jeden z plecaków. Dopiero po jakimś czasie orientujemy się, że przez nową dziurę w plecaku co nieco wypadło i utonęło gdzieś za nami w brudnym szlamie.",
        rule: "Odrzuć dowolne 3 żetony ze Stosu Znalezisk (jeśli jest ich mniej, odrzuć wszystkie).",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s11",
        text: "Słyszeliśmy, że ten kolektor jest bezpieczniejszy od reszty, ale nasze informacje okazują się przedawnione. Schodzimy w dół cementowej studni, zatykając szmatami nosy. Miało być płytko, ale nie jest. Dołem płynie obrzydliwa, żółtawa maź. Stoimy w niej po kolana, rozglądając się na boki. Nic, wszędzie ciemność. Kanał wygląda na niedawno zalany - przed sobą dostrzegamy zarys jakiejś prowizorycznej zapory.",
        rule: "",
        show1: true,
        transText1: "Spróbujemy sforsować przeszkodę",
        changeTo1: 51,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wybór tej drogi nie był dobrym pomysłem. Wracajmy do domu, na dziś wystarczy - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY."
    },
    {
        id: "s12",
        text: "",
        rule: "",
        show1: true,
        transText1: "JEŚLI W TEJ EKSPLORACJI KANAŁÓW BIERZE UDZIAŁ TYLKO 1 POSTAĆ",
        changeTo1: 94,
        show2: true,
        transText2: "JEŚLI WIĘCEJ - WYBIERZ 1 Z OBECNYCH TU POSTACI",
        changeTo2: 54,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s13",
        text: "Jest tak ciemno, że czujemy się niemal jak ślepcy, wymacując słabym promieniem niczym białą laską fragmenty drogi tuż przed sobą. Brodzimy po kolana w mętnej wodzie, gdy nagle dostrzegamy w oddali światło uchylonej studzienki kanalizacyjnej. I ruch tuż przed nami... ktoś się zbliża! Mężczyzna przytrzymuje przy ustach palec, w jego oczach widzimy lęk. Daje nam ręką znak, abyśmy natychmiast się wycofali. Wygląda, jakby bał się, że ktoś go usłyszy... Dookoła jednak nikogo nie ma. Czyżbyśmy trafili na kolejnego szaleńca?",
        rule: "",
        show1: true,
        transText1: "Wycofajmy się. Potem będzie czas na zadawanie pytań",
        changeTo1: 93,
        show2: true,
        transText2: "Pytamy, co tak bardzo go przestraszyło",
        changeTo2: 66,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s14",
        text: "Ta część kanałów rzadko jest odwiedzana przez żywych. Czarne ściany tunelu i leżące w wodzie zwęglone ubrania przypominają o tym, co kiedyś tu zaszło. Gdy trwała ewakuacja dzielnicy, żołnierze zza rzeki w okrutny sposób postanowili rozprawić się z partyzantami. Wpompowali do kanałów benzynę, którą następnie podpalili. W milczeniu przechodzimy przez pomieszczenie pełne szczątków poległych, starając się nie patrzeć na mijane ciała.",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = zapisz \"Lęk, s14\" na Pustym żetonie i połóż go na karcie danej Postaci. Od teraz aż do końca Kampanii, za każdym razem gdy dana Postać weźmie udział w Eksploracji Kanałów, podnieś jej Depresję o 1. Przy wyniku wyższym = nic się nie dzieje.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s15",
        text: "Najpierw musieliśmy przygarbić plecy, potem poruszać się na czworaka. Teraz czołgamy się pod coraz niższym sklepieniem wąskiego tunelu. Umysł płata figle i zdaje nam się, że jest już zbyt ciasno, by swobodnie zaczerpnąć tchu. Pora zadać sobie pytanie, czy pełzniemy dalej, czy lepiej w tym momencie zrezygnować i wrócić.",
        rule: "",
        show1: true,
        transText1: "Zaszliśmy już za daleko, by teraz rezygnować",
        changeTo1: 57,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wracamy - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY."
    },
    {
        id: "s16",
        text: "Butelki... Wszędzie walają się rozbite butelki. Stąpamy po kawałkach strzaskanego szkła, zaścielając małe pomieszczenie. Ktoś tu pomieszkiwał. Brudne szmaty pachną mocnym alkoholem i ledwie wyczuwalną wonią papierosów. W zagłębieniu przy rurze udaje nam się wymacać skórzany portfel z plikiem podrobionych paszportów, wyrabianych zapewne przez fałszerza. Musiał być dobry w swoim fachu. I drogi. Przy swojej poduszce trzyma prawdziwy skarb. Przednie whiskey, za które wielu byłoby gotowych zabić. Taka butelka nie może się zmarnować!",
        rule: "Zapisz \"Whiskey, s16\" na Pustym żetonie i połóż go na Stosie Znalezisk. Traktuj go jak zielony żeton o wartości 30 i wadze 1. Ponadto w dowolnym momencie możesz użyć Whiskey identycznie jak Spirytusu",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s17",
        text: "Odgłosy naszych kroków wystarczyły, by napędzić stracha żyjącemu w kanałach biedakowi. Mężczyzna już z daleka unosi ręce w górę, słabym głosem błagając o zmiłowanie. Podchodzimy bliżej. Był torturowany. Skóra na jego policzkach wygląda tak, jakby ktoś przystawił do niej rozgrzane żelazko. Nieznajomy kuli się pod ścianą, biorąc nas za swoich oprawców. Nieśmiało unosi ku nam rozbiegany wzrok, sunąc dłonią po spieczonym policzku. \"Ja nie chcę tam wracać, do nich... oni... oni...\" - biedak bełkocze niewyraźnie. Widzimy, że ten człowiek przeszedł przez horror, który kosztował go zbyt wiele, i jego umysł się poddał. Teraz zachowuje się jak kilkuletnie dziecko, rozglądające się w obawie przed kryjącymi się w każdym zakamarku potworami.",
        rule: "",
        show1: true,
        transText1: "Pozwalamy mu wędrować z nami aż do wyjścia z kanałów",
        changeTo1: 83,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "\"Bo zaprowadzimy cię z powrotem do nich!\" Pozbywamy się jego towarzystwa, posuwając się do gróźb. WRÓĆ DO GRY "
    },
    {
        id: "s18",
        text: "Płacz, śmiech, złorzeczenia. Trzy dostarczone listy i trzy róźne reakcje odbiorców. Trudno wymazać z pamięci zrozpaczoną twarz matki, kiedy odbierała od nas list informujący o śmierci jej syna... Wciąż słyszymy w myślach śmiech ulgi na wieść o tym, że dziewczyna żyje, a co więcej, wciąż wierzy w swoje ślubne plany... Wzdrygamy się na wspomnienie, jak kobieta miotała w naszą stronę wiązanki przekleństw, a potem wycelowała broń i odbezpieczyła ją. Kazała nam się wynosić i nie chciała nawet słyszeć o liście od kogoś, kogo najwyraźniej wolała uznać za zmarłego. To tylko trzy fragmenty czyjegoś życia przerwanego przez wojnę.",
        rule: "Usuń żeton Listów z gry. Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = obniż Depresję danej Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s19",
        text: "Sylwetki uzbrojonych postaci stojących obok barykady wyraźnie odcinają się od mroku wielkiej hali. Mężczyźni i kobiety wydają się celować w naszą stronę. W pierwszej chwili chcemy zerwać się do ucieczki, dopiero potem przychodzi refleksja. Nikt nas nie ściga, nie krzyczy, nie strzela. Nikt się nie rusza... Podchodzimy bliżej nieruchomych postaci, czując, jak z każdym krokiem włosy coraz bardziej jeżą nam sie na głowie. Mówiono nam o prtyzantach wykorzystujących w lesie kukły żołnierzy, aby w ten sposób odstraszyć wroga, jednak nigdy nie słyszeliśmy, aby używano w tym celu prawdziwych ciał. Martwych oparto o ściany z pomocą desek i przyczepiono im atrapy broni, najwyraźniej licząc, że widoczne z oddali sylwetki wystarczą, by przegnać stąd intruzów. Ruszamy dalej.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s20",
        text: "Przemierzamy labirynt kolektorów i docieramy do wysuszonego kanału. Zardzewiała drabinka prowadzi wysoko w górę, w stronę krat kanalizacyjnych. Zaczynamy się wspinać i natychmiast przestajemy, keidy na nasze głowy spadają drobiny papierosowego popiołu. Ktoś jest nad nami, na ulicy. Dwie ciemne sylwetki majaczą zaraz nad kratką ściekową. Ich rozmowę zagłusza warkot silnika i wypowiadany ostrym tonem rozkaz zatrzymania pojazdu. Serca biją nam szybciej... Wygląda na to, że dotarliśmy pod jakiś odległy posterunek kontrolny. \"Co przewozicie? Ach, jedzenie - mówicie? A to pod plandeką to też jest jedzenie?\" - słyszymy głos, a zaraz potem odgłosy szamotaniny i dwa głuche wystrzały. Padające ciała zasłaniają nam widok. Gdy rozlega się kolejny strzał, z przerażeniem widzimy, jak kula przeszywa leżące ciało i rykoszetem odbija się w studzience, w której tkwimy. Spadają na nas pierwsze krople krwi. Najciszej, jak potrafimy, schodzimy na dół i ruszamy dalej...",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = podnieś Depresję danej Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s21",
        text: "Jest tu zimno i mokro, a w powietrzu czuć wyraźny zapach stęchlizny i wilgoci. Nagle dołącza się inny zapach... zapach pieczonego mięsa! Zaburczało nam w brzuchach i ślina podbiegła pod języki. W jednym z niewielkich, technicznych pomieszczeń dostrzegamy tlący się żar. Ktoś tu niedawno był. Na niedopalonych do końca kawałkach drewna zostały kawałki niedojedzonego mięsa. Trzeba wyciągać szybko, bo się spalą. Tylko że to... pieczone szczury.",
        rule: "",
        show1: true,
        transText1: "Częstujemy się. Głodny człowiek nie wybrzydza",
        changeTo1: 58,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Nie ryzykujemy, mięso może być zatrute - WRÓĆ DO GRY"
    },
    {
        id: "s22",
        text: "Wojna dotarła do kanałów już dawno, ale nigdy nie dawała tak silnie o sobie znać... Z bocznych korytarzy kanałów wychodzą żołnierze w pełnym rynsztunku. W oddali słyszymy odgłosy wystrzałów. To ludzie broniący bariery błagają o wsparcie, próbując odeprzeć nieoczekiwany atak zza rzeki. W ciemności każdy strzał jest widoczny jak wystrzelona w nocy raca. \"Nie widzimy ich! Gdzie oni są?! Dawajcie wsparcie! Słyszycie?! Oni zaraz będą w mieście!\" - echem niosą się wściekłe krzyki radiowca. Jakiś żołnierz zagradza nam przejście. Pyta o dokumenty, których nie mamy, i ostrym tonem odsyła nas z powrotem. To koniec na dziś, trzeba wracać, utro możemy poszukać podziemnej drogi do innej części miasta.",
        rule: "Przerwij Eksplorację Kanałów.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s23",
        text: "Owalny, zabytkowy tunel, którym idziemy, służył dawniej jako zbiornik na wodę. Nad sobą słyszymy odgłosy tłoków i po chwili docieramy do wciąż czynnej stacji pomp położonej na przedmieściach. Przez kratę ściekową w podłodze dostrzegamy pomieszczenie położone jeszcze głębiej, pod nami. A także krążących po nim ponurych żołnierzy. Są podenerwowani i byle szelest wystarczy, aby sięgneli po broń. \"Ilu ich jest?\" - pyta jeden z nich. W drzwiach pojawia się młody chłopak, odziany w mundur i uzbrojony w bagnet. \"Jelena naliczyła pięciu w głównej hali i dwóch w śluzie. Może ich być jeszcze więcej, mogą być gdziś blisko...\" - odpowiada i nagle wybałusza oczy, potyka się i pada, a po posadzce rozlewa się plama krwi. Ktoś rozbija lampę i pomieszczenie spowija całkowita ciemność. Nagle rozlegają się strzały, a w urywanym blasku dostrzegamy ciemne sylwetki, noże i błyszczące lufy. Żołnierz, którego obserwowaliśmy, pada raniony serią z broni automatycznej. Zaczęło się. Mamy chwilę, by wycofać się głębiej do podziemnych tuneli. Wolimy nawet nie myśleć, co stanie się, jeśli któraś ze stron przejmie pełną kontrolę nad wodą w mieście.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s24",
        text: "Ciasny tunel przed nami można pokonać jedynie na czworakach. Najpierw zapuszczamy się na rekonesans i po kilku metrach gwałtownie przystajemy. Po drugiej stronie przejścia jarzy się blade światło, najpewniej pochodzące z latarki. Nagle światło zaczyna mrugać i po chwili gaśnie. Poza popiskiwaniem głodnych szczurów nie słyszymy wokół żadnych innych odgłosów. Ludzi, szumu wody. Nic.",
        rule: "",
        show1: true,
        transText1: "Ktokolwiek jest po drugiej stronie, na razie nie zdradza złych zamiarów. Idźmy dalej.",
        changeTo1: 67,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zawracajmy. To może być jakaś pułapka - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY"
    },
    {
        id: "s25",
        text: "Przekreślone koło to symbol, który od jakiegoś czasu towarzyszy naszym krokom. Namalowany kredą na ścianie być może do niedawna służył do oznaczania bezpiecznej drogi dla uchodźców albo pomagał nie zgubić się w ciemności ich katom. Nie dowiemy się tego, jeśli sami nie sprawdzimy. Tylko czy warto ryzykować?",
        rule: "",
        show1: true,
        transText1: "Sprawdźmy, gdzie może doprowadzić nas ten znak",
        changeTo1: 96,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wybierzmy inną drogę - WRÓĆ DO GRY"
    },
    {
        id: "s26",
        text: "Tunel zakręt, tunel i ani się obejrzymy, a wracamy do tego samego rozwidlenia korytarzy. Błądzimy tak już dobre kilka godzin. Próbujemy wybrać inną drogę, oznaczając naszą trasę znalezionym kawałkiem cegły, ale skutek jest zawsze podobny. W ciemności tracimy poczucie czasu. Byle szmer bierzemy za odgłos ludzkich stóp, choć za jedynych towarzyszy mamy wygłodniałe szczury. Wychodzimy w następny ślepy korytarz. Pozornie. W kratach zieje wyrwa umożliwiająca nam przejście na drugą stronę. Nareszcie! Z ulgą dostrzegamy odsłoniętą pokrywę włazu kanalizacji i wpadające przez nią blade światło słońca.",
        rule: "Podnieś Zmęczenie dowolnej z obecnych tu Postaci o 1. Po wyjściu z Kanałów zaczniesz z 2 kartami Przeszukiwania mniej w talii Nieznanego. Możesz natychmiast wyjść z Kanałów do dowolnego z 3 Miejsc",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s27",
        text: "Jęki rannego słyszymy znacznie dłużej, niż to możliwe. Gdy zdajemy sobie sprawę, że to już tylko nasze złudzenie, w końcu cichną.",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = podnieś Depresję danej Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s28",
        text: "Podchodzimy do ściany niewielkiego pomieszczenia. Ściek spływa tu prosto do położonego na przedmieściach jeziora, nad którym dawniej co weekend ludzie wypoczywali po trudach tygodnia. Teraz ten \"raj\" z przesłości jest zupełnie niedostępny, mimo że oddzielają nas od niego jedynie kraty i zmętniała woda. W jej odbiciu dostrzegamy poruszające się białe chmury, cięte śladami odrzutowych samolotów. Las na drugim brzegu wygląda na nietknięty wojną, w przeciwieństwie do piętrzących się po prawej, dymiących ruin dzielnicy willowej. Biurowce na wschodzie będą następne. Jak na zwolnionym filmie, obserwujemy otwierające się klapy samolotów i wypluwane przez nie bomby. W wodnej taflii odbijają się wszystkie odcienie czerwieni. Z rezygnacją odwracamy wzrok i wracamy z powrotem do tunelu. Do naszego własnego piekła.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s29",
        text: "Kobieta leży przysypana, tylko część głowy wystaje spod gruzu. Po śladach na skórze wnioskujemy, że umarła kilka dni temu. Na na sobie szary mundur. Przypięty na piersi znak świadczyo tym, że należała do rebeliantów. Spluwamy na ziemię. \"My\" czy \"oni\" przestało już mieć znaczenie. Kto ma broń, ten zabija, po prostu. Przy jej ciele znajdujemy torbę wypełnioną listami.",
        rule: "",
        show1: true,
        transText1: "Rozdzieramy listy i przeglądamy",
        changeTo1: 59,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Rzucamy je w błoto i idziemy dalej - WRÓĆ DO GRY"
    },
    {
        id: "s30",
        text: "Wąska kładka prowadzi nad podziemnym zbiornikiem ścieków. W oddali widzimy dwie szamoczące się sylwetki. Barczyści mężczyźni w mundurach ociekają krwią i szlamem. Jeden z nich uderza przeciwnika w brzuch, posyłając go na krawędź kanału. \"Wybrałeś złą stronę, bracie. Powinniśmy się trzymać razem\" - mówi z triumfem. Głowa jego ofiary zwisa w dół przepaści. Jeszcze chwila i mężczyzna runie w dół. \"Święta racja, bracie, powinniśmy być razem\" - odpowiada tamten cicho. Resztkami sił mocno chwyta przeciwnika za ramiona i ciągnie go ze sobą. Guchy odgłos upadku odbija się od ścian, a chwilę później dwa bezwładne ciała kołyszą się w czarnej wodzie pod nami.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s31",
        text: "Czołgamy się przez ciasny tunel techniczny, uważając na biegnące obok kable, choć pewnie prąd od dawna juz w nich nie płynie. Od metalowych ścian odbija się szum wody, a także bardziej niepokojący dźwięk. Cichy płacz dziecka dobie gdzieś spod podłogi i staje się głośniejszy w miarę jak nasz korytarz zaczyna zakręcać. Mamy nadzieję, że uda nam się znaleźć porzucone w tunelu dziecko, ale nasz korytarz odbija w lewo - oddalamy się coraz bardziej i bardziej od źródła płaczu, prowadzeni przez nieubłagany labirynt przejść. Zaciskamy zęby w bezsilnej rezygnacji - nie możemy nic zrobić, żeby pomóc porzuconemu malcowi.",
        rule: "Podnieś Depresję 1 z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s32",
        text: "Niektóre dzielnice broniły się dłużej, niż wszyscy sądzili. W brudnym szlamie natrafiamy na upchane do zapleśniałej torby fragmenty relacji z odwrotu jakiejś walczącej grupy. \"Cegielnia stracona. Dostaliśmy z dowództwa rozkaz, by przebić się do centrum. Zeszliśmy do kanałów z oddziałem Petrovicia. Żeby dojść do miejsca przeznaczenia, musieliśmy przeprawić się przez zalany kolektor. Przejście kilometra w gęstym szlamie zajęło trzy godziny. Pomagaliśmy sobie długimi drążkami, żeby utrzymać się na powierzchni. Nie było łatwo. Od wyziewów kilku naszych dopadły halucynacje. Zostawiliśmy ich za sobą. Nie oglądaliśmy się do tyłu. Szliśmy dalej. Aż do tego miejsca. Za nami wróg. Przed nami koniec korytarzy. Wygląda na to, że dotarliśmy już do kresu.\"",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s33",
        text: "W ścianie kanału zieje wyłom, przez który dostrzegamy fragmenty biegnących torów niedokończonego, podziemnego tramwaju. Obok spoczywa porzucony sprzęt budowlany. Srebrne wiertła i uśpione buldożery. Jeden z nich budzi się nagle, jasny blask pada prosto na nas. \"Wi... wi... widzieliście tam kogo?\" - łysy żołnierz wspierający się na kulach wyłania się z kabiny pojazdu. Wygląda na przerażonego. Czyżby był tutaj sam?",
        rule: "",
        show1: true,
        transText1: "Odejdźmy, zanim wezwie posiłki",
        changeTo1: 87,
        show2: true,
        transText2: "Zachowujmy się spokojnie i porozmawiajmy z nim",
        changeTo2: 52,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s34",
        text: "Zaglądamy do tego pomieszczenia i przecieramy oczy ze zdumienia. Niewielkie, szaro-białe grzyby pokrywają kilka rzędów półek. To pieczarkarnia! Ktoś hoduje tu grzyby, dba o uprawę. I ma pecha, bo właśnie znaleźliśmy jego skarb. Trudził się, ale z efektów skorzysta ktoś inny.",
        rule: "",
        show1: true,
        transText1: "Pakujemy do plecaków, ile się da",
        changeTo1: 70,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wychodzimy. Ktoś włożył w to za dużo pracy, by wszystko mu teraz odebrać - WRÓĆ DO GRY"
    },
    {
        id: "s35",
        text: "Korytarz kończy się kamiennym usypiskiem, zagradzającym dalszą drogę. Świst powietrza docierający znad zwaliska świadczy o tym, że jesteśmy blisko powierzchni. Przez szpary w kamieniach przebija się słabe, migające światło. Możemy spróbować odgruzować wyjście, ryzykując, że część zwaliska się na nas obsunie, lub poszukać innej drogi.",
        rule: "",
        show1: true,
        transText1: "Spróbujmy się wspiąć",
        changeTo1: 85,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Szukamy innej drogi - WRÓĆ DO GRY"
    },
    {
        id: "s36",
        text: "Przez moment czujemy się prawie jak dzieci podglądające przez dziurkę od klucza swoich rodziców. Tylko, że tu nie ma drzwi, jest za to wyrwa w ścianie i ta dwójka, przycupnięta na rusztowaniach u wejścia do dużej, podziemnej hali. Chłopak należy zapewne do rebeliantów. Rumieni się jak burak, ilekroć spogląda na wychudzoną twarz siedzącej obok dziewczyny. \"Ja ci chciałem to powiedzieć, bo jak dziś wyjdę, to może nie być szansy. Mi to już jedno. Mogę nie wrócić, byle tamtym się dostało\" - wyznaje rwącym głosem. Dziewczyna spogląda na niego wyczekująco, pozwalając mu się objąć. \"Bo ja... Od tamtego razu, gdy myśmy im stawili opór, to ja myślę o tobie, wiesz...\" - Dziewczyna przerywa mu i składa łagodny pocałunek na jego ustach. \"Nie daj się zabić, Dario. Będę czekała\" - mówi cicho, obdarzając go smutnym uśmiechem. Udając, że nie widzimy tej dwójki, ruszamy przez halę.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s37",
        text: "Obżarstwo na wojnie bywa równie zgubne, co głód. Mężczyzna, którego mamy przed sobą, zastygł przy samym wyjściu z kolektora z wyrazem niemego zdumienia na twarzy, tak jakby do końca nie mógł uwierzyć w swój żałosny los. Pucułowaty na twarzy, potężnej postury, odziany w drogi garnitur, próbował do samego końca walczyć o życia. Był zapewne przedsiębiorcą lub biznesmenem. Uparcie wierzył, że z pomocą łapówek uda mu się uciec z miasta. Jednak źle wyliczył cenę za swoją ucieczkę, a kiedy utknął w tunelu, nikt nie pośpieszył mu na ratunek. Nie miał przy sobie zbyt wiele. Widocznie nie jesteśmy pierwszymi, którzy trafili na tego nieszczęśnika.",
        rule: "Dodaj 1 Część Elektryczną i 3 Papierosy do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s38",
        text: "Zaglądamy do niewielkiego pomieszczenia i szybko wycofujemy się o kilka kroków, próbując wyrzucić z pamięci przerażający widok. Dziesiątki ciał, wychudzonych, sinych, bezładnie rzuconych jedno na drugie jak sterta odpadków. W sklepieniu pomieszczenia widać zamknięty właz. Tamtędy pewnie zrzucano ciała. Kolejny masowy grób, kolejny dowód bezmyślnej eksterminacji ludzkiego życia...",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = podnieś Depresję danej Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s39",
        text: "Smród, wilgoć, ciasnota. Trzeba tu iść w przygarbionej pozycji, prawie na czworakach. Już po kilku minutach bolą plecy, co pogłębia jeszcze ciężar niesionych plecaków. Na nos musimy naciągnąć szmaty, smród sprawia, że kręci nam się w głowach. Każdy krok to plusk, bo brodzimy po kostki w mętnej, cuchnącej brei: plusk, plusk, plusk. Wtem czyjś but zagłębia się w coś miękkiego, nie słychać plusku. Światło latarki pozwala odkryć makabryczne znalezisko - rozkładające się zwłoki kobiety. Trzeba je minąć, ocierając się o mokrą ścianę. I iść dalej, by tu nie utknąć, jak ta biedaczka. W kieszeni ląduje znaleziony przy niej scyzoryk.",
        rule: "Dodaj 1 Nóż do Stosu Znalezisk",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s40",
        text: "Próbowali uciec - domyślamy się po zamarłych na wieczność przerażonych twarzach. Chłopak i dziewczyna, tak jak my, musieli zgubić drogę w kanałach. Zamiast do upragnionego wyjścia dotarli do kraty wychodzącej na ciemną rzekę. Oboje wyglądają, jakby zasnęli przytuleni twarzą do stalowych prętów. Domyślamy się, że zmarli z głodu lub z wycieńczenia. Dziewczyna była ranna. Pielęgniarski uniform pokrywa zakrzepła krew. Obandażowana dłoń mężczyzny opiera się na jej barku. Cuchnie zgnielizną. Kto tu kogo próbował uratować? Echa wystrzałów dobiegające z wnętrza kanałów wyrywają nas z chwilowej zadumy. W tych tunelach nie jest bezpiecznie. W tych tunelach czai się śmierć. Tylko śmierć...",
        rule: "Wybierz 1 z obecnych tu Postaci. Zapisz \"Lęk, s40\" na Pustym żetonie i połóż go na karcie tej Postaci. Od teraz aż do końca Kampanii, za każdym razem gdy ta Postać weźmie udział w Eksploracji Kanałów, podnieś jej Depresję o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s41",
        text: "Porzucony przy wąskim przejściu plecak pełen jest notatek i szkiców. Jest w nim coś jeszcze - mocno zniszczona, cle chyba wciąż sprawna kamera. Wsuwamy do niej kasetę i sprawdzamy ostatnie magranie. Drżący obraz przedstawia tłum uchodźców zmierzających ku posterunkom kontrolnym. Wezbrana fala ludzi napiera na strażników i rozstawione po obu stronach barierki. W tle słychać strzały, a gdzieś blisko płacz. Kolejne ujęcie - baraki. Wszędzie powiewają flagi tych zza rzeki. Trwa musztra. Cięcie. Młodzi mężczyźni opowiadają o patriotyzmie. Chwalą się, co zrobili kobietom z wioski. Nie da się tego słuchać. Cięcie. Znajome, ciemne kanały, sylwetki ludzi. Operator ma się pośpieszyć, inaczej zostanie z tyłu. Cięcie. Ostatnie ujęcie - blada twarz, jakieś niewyraźne słowa. Poraniona dłoń, która wyłącza kamerę.",
        rule: "Dodaj 2 Części Elektryczne do Stosu Znalezisk",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s42",
        text: "Chłopak uczepił się kraty blokującej przejście na drugą stronę tunelu i za nic nie chce nas puścić. Błędnym wzrokiem wpatruje się w skapujące ze ścian kropelki wody i czarną pieczarę, w której zniknęli przedtem jego towarzysze. \"Ja widziałem, mówię wam, gdzieś jest wyrwa w tych kratach, tam, tam... na drugą stronę. Ja zostałem z tyłu i dlatego mnie to spotkało... Czemu nie zaczekaliście pięć minut?\" - rzuca w naszą stronę z oskarżycielskim tonem, wyciągając przed siebie chudy palec. Chyba bierze nas za swoich towarzyszy. Cofamy się w obawie przed atakiem szaleńca. Nic takiego nie ma jednak miejsca. Chłopak przygląda się nam, jakby z wahaniem, po czym odwraca głowę i znowu chwyta za kratę. \"Pięć minut, tylko pięć minut\" - słyszymy za sobą echo jego głosu.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s43",
        text: "Tak musi pachnieć w piekle. Przewiązujemy usta i nos kawałkami szmat. Niewiele do daje. Zapach nieczystości jest tak intensywny, że z każdym krokiem żołądek coraz silniej protestuje. Stajemy w ścieku i z trudnością próbujemy złapać oddech. Rozglądamy się. Nie my pierwsi próbujemy tędy przejść. Przy ścianie siedzi martwa postać, opatulona szmatami. Z daleka przypomina mumię. Musiała próbować przeprawy w ten sam sposób, co my. Dalsza wędrówka tym tunelem równa się samobójstwu. Tym razem musimy zawrócić do domu. Może innym razem, gdy wybierzemy inną drogę, zajdziemy dalej.",
        rule: "Przerwij Eksplorację Kanałów. Podnieś Chorobę dowolnej z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s44",
        text: "Czy to może być... radio? Biały szum wybija się ponad odgłos płynącej w kanałach wody i z każdym kolejnym krokiem staje się coraz lepiej słyszalny. Zachowujemy ostrożność, nie wiedząc, kto o zdrowych zmysłach próbowałby łapać sygnał w podziemiach. Nikt z żywych, jak się okazuje. Gdy wchodzimy do niewielkiego pomieszczenia, spod ciała chłopca wybiega cały tabun szczurów. Jego martwa dłoń w beznadziejnym geście obejmuje pokrętło radia. W błękitnych jak u lalki oczach wciąż widać strach. Zmarł niedawno, być może z głodu. Co robił w ostatnich chwilach? Czy w akcie desperacji próbował wykorzystać szum z radia, aby odstraszyć szczury? A może miał nadzieję, że z jego pomocą zwabi do swojej kryjówki kogoś, kto go ocali? Jeśli to mieliśmy być my, spóźniliśmy się o co najmniej kilka godzin. Zamykamy chłopakowi oczy i zabieramy z jego rąk radio. Tam, dokąd odszedł, raczej nie będzie go potrzebował.",
        rule: "Jeśli w Schronieniu nie ma Radia, znajdź kartę Radia w talii Sprzętów i dodaj ją do Stosu Znalezisk. Po powrocie do domu połóż ją za darmo na dowolnym pustym polu Schronienia. Jeśli w Schronieniu jest już Radio, dodaj 2 Części Elektryczne do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s45",
        text: "Instynktownie schylamy głowy, kiedy słyszymy nad sobą głośne echa wybuchów. Ataki na dzielnicę przemysłową trwają od tygodnia, ale dziź wydają się szczególnie agresywne. Jeśli ktokolwiek był teraz tam, nad nami, już po nim. Spluwamy w stronę prowizorycznej bariery wzniesionej z kawałków mebli. Walki musiały dotrzeć aż tutaj. Zapewne w ten sposób uchodźcy do niedawna próbowali się bronić. Co i rusz potykamy się o świeże ciała lub porzucony w pośpiechu dobytek. Jest tego całe mnóstwo. Mordercy zza rzeki tutaj nie próźnowali, a ich oddziały dalej mogą przeczesywać kanały. Z drugiej strony to pobojowisko może być warte ryzyka...",
        rule: "",
        show1: true,
        transText1: "Przeszukajmy to miejsce",
        changeTo1: 89,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zawracamy, póki czas. Niedawno mijaliśmy inny korytarz, lepiej sprawdzić tamtą drogę... - WRÓĆ DO GRY"
    },
    {
        id: "s46",
        text: "Niedawne opady sprawiły, że poziom wody w niektórych tunelach jest zbyt wysoki i skutecznie uniemożliwia nam przejście. Trzymamy się szerszych tuneli, z niepokojem wsłuchując się w odległy szum. Jesteśmy gdzieś w pobliżu rzeki. Z rur nad naszymi głowami skapują pojedyncze krople. Przejście przed nami blokuje wysoka krata - znów trzeba szukać innej drogi. Schodzimy niżej. Rwący ściek płynie wartkim nurtem i spływa grubą rurą prosto do rzeki. Wygląda na to, że to jedyna droga na zewnątrz.",
        rule: "",
        show1: true,
        transText1: "Zaryzykujmy spływ wraz z nieczystościami",
        changeTo1: 74,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Skok do rzeki byłby szaleństwem, lepiej wracajmy - PRZERWIJ EKSPLORAJCĘ KANAŁÓW I WRÓĆ DO GRY"
    },
    {
        id: "s47",
        text: "Trasa, którą obraliśmy, musi być często używana. Na co trudniejszych fragmentach znajdują się grube liny zabezpieczające przed upadkiem. Przy spływie ścieku znajduje się prowizoryczny posterunek rebeliantów. Jasny snop światła z latarki nagle nas oślepia. \"Kto tam?\" - chłopak, który zadaje pytanie, ma na sobie zbyt duży wojskowy mundur. Spogląda na nas nieufnie, wyciągając z ust żarzącego się papierosa. \"Tu jest strefa zamknięta. Przepustkę macie?\" - pyta agresywnym tonem. Ze spokojem próbujemy wyjaśnić, że zabłądziliśmy w kanałach. Staramy się nie wzbudzić podejrzeń, ale mamy pecha. Trafiliśmy na służbistę. Młodzik woła swoich towarzyszy i zaczyna się przesłuchanie. Trwa to długo i wcale nie rozwiewa wrodzonej nieufności chłopaka, w którego rękach spoczywa nasz los...",
        rule: "",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 82,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s48",
        text: "Martwy mężczyzna leży zawinięty w koce i wtula się policzkiem w kamienną ścianę kanału. Sądząc po mundurze, był łącznościowcem. Plecak, który przy nim znajdujemy, pełen jest paierów datowanych na okres, gdy wojna dopiero docierała do miast. Część z nich przedstawia nieaktualne mapy kanałów. Wiele kolektorów zalano, a przy reszcie można natknąć się na nieoznaczone barykady i pułapki. Mimo wszystko mapy mogą okazać się bardzo przydatne.",
        rule: "Napisz \"Wojskowa Mapa Kanałów, s48, I I\" na Pustym żetonie i połóż go na Stosie Znalezisk. Traktuj go jak szary żeton o wartości 6 i wadze 0. Podczas dowolnej Eksploracji Kanałów, zamiast dobierać kolejny kafelek Mapy Kanałów, możesz skreślić 1 kreskę z żetonu, aby natychmiast wyjść z Kanałów do dowolnego z 3 Miejsc. Gdy skreślisz ostatnią kreskę, nie możesz już więcej użyć Wojskowej Mapy Kanałów, ale żeton nadal posiada wartość 6.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s49",
        text: "Szeroki kanał przed nami wygląda jak porzucone składowisko mebli. Tapczany, ozdobne szafy, a nawet stłuczone telewizory tworzą wysoką barierę, przywodzącą na myśl surrealistyczne dzieło sztuki. Dookoła panuje cisza, nie ma śladów po jakiejkolwiek walce. Podchodzimy bliżej i nagle odskakujemy od bariery. Po drugiej stronie ktoś jest i groźnie się nam przygląda. \"Kto idzie? Podejdźcie no bliżej!\" - żąda mężczyzna zachrypnietym głosem.",
        rule: "",
        show1: true,
        transText1: "Próbujemy się wycofać",
        changeTo1: 69,
        show2: true,
        transText2: "Podchodzimy tak, jak kazał",
        changeTo2: 95,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s50",
        text: "Stracili swoją odwagę i nie mają dokąd pójść... W oddali widzimy grupkę wojskowych z niechlubnego batalionu, którzy rozsiedli się w wielkiej, podziemnej hali. W zniszczonych strojach, z opuszonymi głowami, czują się jak obcy we własnym mieście. Mieli za zadanie ochraniać lotnisko na zachodzie, ale kiedy z odległych wzgórz spadła lawina pocisków, a z nieba deszcz rakiet... opuścili stanowiska. Stchórzyli. Zapiliby się na śmierć, gdyby posiadali wystarczający zapas alkoholu. Są teraz jak duchy wałęsające się po mieście bez określonego celu. Wolimy nie mieć z nimi do czynienia. Wycofujemy się po cichu i wybieramy inną drogę.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s51",
        text: "Zapora wykonana jest z kawałków blachy owiniętych drutem i jej pokonanie wymaga sporo wysiłku. Jedno z nas rozrywa ubranie, zahaczając ramieniem o drut. Z rany leniwie kapią kropelki krwi.",
        rule: "",
        show1: true,
        transText1: "Nie mamy przy sobie Opatrunku. Lepiej wróćmy do domu i przunajmniej przemyjmy ranę",
        changeTo1: 80,
        show2: true,
        transText2: "To nic takiego, chodźmy dalej...",
        changeTo2: 64,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zabandażujmy i zdezynfekujmy ranę - ODRZUĆ 1 OPATRUNEK ZE STOSU ZNALEZISK I WRÓĆ DO GRY"
    },
    {
        id: "s52",
        text: "Mężczyzna podupada na duchu, gdy mówimy mu, że nikogo nie spotkaliśmy w kanałach. Wyznaje, że jego kompani wyruszyli do kanałów kilka godzin temu. To miała być krótka wyprawa. Z pomocą podkładów kolejowych mieli umocnić barykady, by utrudnić wrogowi przejście. Do tej pory nie wrócili. Żołnierz częstuje nas herbatą ze zdobionego imbryka i kawałkiem chleba, uważnie lustrując nas wzrokiem. Po kilku chwilach nasz nowy kompan otwiera butelkę wódki. Kiedy pijackim głosem zaczyna wykrzykiwać imiona zaginionych, orientujemy się, że sprawy zaszły za daleko. Zostawiamy mężczyzne samego z jego żalem. Czym prędzej znikamy w ciemności.",
        rule: "Obniż Głód 1 z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s53",
        text: "Tupot naszych butów i głośne chlapnięcia, gdy trafiamy na kałuże brei. rozlegają się niczym z potężnych głośników. To wystarcza, by napastnicy rzucili się do ucieczki, nawet nie wiedząc przed kim. Gdy dobiegamy do leżącego człowieka, ten próbuje wstać. Na jego czole widać ślad po potężnym uderzeniu. Jedno oko zaczyna już puchnąć. Mimo to uśmiechamy się - nic mu nie będzie, ot, nauczka. Starszy mężczyzna nazywa się Viktor. Cóż, niech wraca z nami, przynajmniej aż do wyjścia z kanałów.",
        rule: "Do końca tej Eksploracji Kanałów Viktor jest z nami. Jeden raz podczas tej wspólnej podróży możemy zdecydować, że to właśnie na Viktora zamiast na 1 z obecnych tu Postaci spadnie efekt pechowego wydarzenia (np. Rana, Choroba, itd.).",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s54",
        text: "Błysk noża jest tak nagły, że nie zostawia nam żadnej szansy na reakcję. Napastnik przywykł do podobnych ataków. Właśnie teraz trzyma ostrze przy szyi jednego z nas. Szare długie włosy opadają na pociągłą twarz. Czarne oczy są jak dwie dopalające się bryłki węgla. \"Dawajcie, co macie, albo go zabiję\" - ostrze nacina skórę przy szyi. To nie są żarty!",
        rule: "",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 81,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s55",
        text: "\"Cholera!\",\"A niech ich!\" - słyszymy wściekłe krzyki za sobą. Jednak żaden strzał nie padł. Może nie mieli amunicji, może bali się hałasu, jaki towarzyszyłby wystrzałom. Ważne, że nie strzelili. Tym razem mieliśmy szczęście.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s56",
        text: "Mężczyzna nie chce nawet słyszeć o ratunku - zbyt dobrze zna swój stan, by łudzić się jakąkolwiek nadzieją. Błaga nas o śmierć, której nikt z nas wolałby nie zadawać. \"Proszę zróbcie to. To będzie dobre...\" - dochodzi do nas stłumiony przez ból głos żołnierza.",
        rule: "",
        show1: true,
        transText1: "Spełnijmy jego prośbę - WYBIERZ 1 Z OBECNYCH TU POSTACI",
        changeTo1: 88,
        show2: true,
        transText2: "Zostawmy go. Nie możemy mu pomóc i nie chcemy mieć jego krwi na swoich rękach",
        changeTo2: 27,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s57",
        text: "Zadawaliśmy sobie to pytanie jeszcze dziesiątki razy. Plecami tarliśmy o ceglany strop, z którego sypały się kawałki gruzu. Jeszcze metr, jeszcze metr, jeszcze kilka. Gdy dotarliśmy do wylotu, wychodzącego na ścianę szerokiego korytarza, poczuliśmy się, jakbyśmy właśnie opuścili piekło...",
        rule: "Podnieś Depresję 1 z obecnych tu Postaci o 1. Jeśli jest tu więcej Postaci, obniż Depresję 1 innej z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s58",
        text: "Nie jest tego wiele, ale będzie smakować wybornie. Szczególnie ta chrupiąca skórka.",
        rule: "Dodaj 1 Surowe Mięso do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s59",
        text: "O dziwo, to zwyczajne listy rodzin. Listy od młodych ludzi, którzy gdzieś tam daleko walczą, wierząc w swoje racje. Nie ma tu tajnych rozkazów, tylko tęsknota, smutek i nadzieja. Kilka adresów udaje nam się rozpoznać. Moglibyśmy dostarczyć te listy, gdybyśmy teraz zawrócili.",
        rule: "",
        show1: true,
        transText1: "Na te listy na pewno ktoś czeka. Weźmy je ze sobą",
        changeTo1: 72,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "W działania partyzantów lepiej się nie mieszać. Niech listy leżą sobie w kanałach - WRÓĆ DO GRY"
    },
    {
        id: "s60",
        text: "Równoległe odnogi kanału wreszcie łączą się w jeden szeroki tunel. Oczekujemy, że osoba, która nas śledzi, wreszcie się ujawni. Ale nie. W korytarzu obok nikogo nie ma. Czyżby nam się tylko przewidziało? Nagle z ciemności dobiega nas głos dziecka. \"Nie zrobicie mi krzywdy?\" - smutna, umorusana błotem dziewczynka wychodzi z ciemności. Chwilę trwa, nim zbiera się na odwagę, aby podejść bliżej. Ma na sobie, brudny, szkolny mundurek. Opowiada nieśmiało, że ma na imię Sara i jest sierotą. Nie ma dokąd wrócić, bo jej internat trafiła bomba. Dziecko spogląda na nas z nadzieją. Widać, że nie jadło od wielu dni. Jeśli pozwolimy dziewczynce iść z nami, będziemy musieli zawrócić do domu.",
        rule: "",
        show1: true,
        transText1: "Przygarniamy sierotę",
        changeTo1: 91,
        show2: true,
        transText2: "Nie możemy opiekować się dzieckiem",
        changeTo2: 73,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    }, {
        id: "s61",
        text: "",
        rule: "",
        show1: true,
        transText1: "Jeśli któraś z obecnych tu Postaci ma Sprawność 2 lub więcej",
        changeTo1: 79,
        show2: true,
        transText2: "Jeśli nie",
        changeTo2: 92,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s62",
        text: "Jesteśmy jak alpiniści próbujący zdobywać ścianę skalną bez odpowiedniego sprzętu. W pewnym momencie poślizhnęliśmy się na kamieniach i omal nie zlecieliśmy w odmęty. Skończyło się na niegroźnych stłuczeniach. Jednak przed nami jest jeszcze gorzej, a rwący ściek znajduje się niemal dziesięć metrów w dole...",
        rule: "UWAGA! Jeśli idziemy dalej, rzuć Czarną Kością za każdą z obecnych tu Postaci (Postać może użyć Sprawności) i wybierz właściwą opcję.",
        show1: true,
        transText1: "Idziemy dalej - Jeśli co najmniej 1 Postać uzyska wynik = 1-2, przestań dalej rzucać",
        changeTo1: 90,
        show2: true,
        transText2: "Idziemy dalej - Jeśli wszystkie Postaci uzyskają wynik = 3-10",
        changeTo2: 76,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "To zbyt ryzykowne, zawracamy - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY"
    },
    {
        id: "s63",
        text: "Nasz towarzysz klęka przy rannym i kończy jego męczarnie. Przez resztę drogi milczy. W zaciśniętej dłoni ściska wojskową odznakę, medal za odwagę.",
        rule: "Dodaj 1 Nóż do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s64",
        text: "Rana piecze żywym ogniem. Zraniony czuje się coraz gorzej i często musi przystawać. Wygląda na to, że do rany wdało się zakażenie. nie mamy pojęcia, jaka to choroba, ale prędkość, z jaką działa infekcja, każe nam obawiać się najgorszego.",
        rule: "Wybierz 1 z obecnych tu Postaci - podnieś jej Rany o 1 i jej Chorobę o 2.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s65",
        text: "Mężczyzna czuje do siebie wstręt za podjęty wybór i nie jest łatwo przekonać go, aby zabrał stąd książki. W końcu niechętnie przystaje na nasz pomysł, wyznając, że w sercu miasta znajduje się druga biblioteka. Gdy ruszamy dalej, widzimy, jak zaczyna sortować książki i układać w paczki, które jest w stanie unieść. Ma nowy cel w swoim zmarnowanym życiu. Przynajmniej na chwilę. Kilka książek dostaliśmy i my. Nawet jeśli ich nie przeczytamy, to zawsze darmowa rozpałka.",
        rule: "Dodaj 3 Książki do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s66",
        text: "Ledwie zaczynamy pytać, gdy mężczyzna z nieznanego powodu rzuca się do ucieczki, znikając nam z oczu. Coś tymczasem rusza się przy otwartym włazie. Słyszymy odgłos, jakby coś metalowego uderzyło o kamień. Mamy ułamki sekund... nim uderzy w nas siła eksplozji. Fala gorejącego ognia rzuca nas na ziemię. Próbujemy ugasić płonące ubranie.",
        rule: "Rozdziel 2 Rany pomiędzy obecne tu Postaci.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s67",
        text: "W płytkim ścieku leży trup. Mężczyzna umarł niedawno. Naszą uwagę przyciąga fakt, że jest pokaźnej tuszy, przynajmniej jak na warunki panujące w mieście. Wygląda, jakby zasnął w kanale. Dopiero po chwili dostrzegamy, że został uderzony w głowę czymś ciężkim, a potem utonął w ścieku. Latarkę znajdujemy zaraz obok. Ma rozładowane baterie, ale wydaje się solidna. Zabieramy ją ze sobą i kierujemy się na powierzchnię.",
        rule: "Dodaj 1 Część Elektryczną do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s68",
        text: "Po zakończeniu interesów Boban opuszcza halę, wskazując nam jeszcze na koniec, którędy najszybciej wydostaniemy się na powierzchnię.",
        rule: "Jeśli chcesz, zamiast dobierania kolejnego kafelka Mapy Kanałów, możesz wyjść do dowolnego z 3 Miejsc.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s69",
        text: "\"Hola, hola dokąd to?\" - wściekły głos dobiega gdzieś zza sterty rupieci.",
        rule: "",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 95,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s70",
        text: "Zrywamy grzyby całymi garściami i upychamy do plecaków i po kieszeniach. Nieważne, że gnieciemy je i kruszymy. Ważne, by zmieścić jak najwięcej. Gdy wychodzimy, pocieszamy się tym, że odrobinę zostawiliśmy właścicielowi.",
        rule: "Dodaj 6 Warzyw do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s71",
        text: "",
        rule: "Dodaj 1 Nóż, 2 Konserwy, 3 Naboje i Broń zabitych Wrogów do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s72",
        text: "",
        rule: "Zapisz \"Listy, s72\" na Pustym żetonie i umieść go na Stosie Znalezisk. Podczas dowolnej fazy Wyprawy (na początku lub na końcu Przeszukiwania) możesz zwrócić 4 karty Przeszukiwania, aby dostarczyć listy pod wskazane na kopertach adresy - patrz skrypt s18 (ZANOTUJ TĄ INFORMACJĘ!)",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Tymczasem WRÓĆ DO GRY"
    },
    {
        id: "s73",
        text: "Sara spodziewała się podobnej odpowiedzi. Sieroty nigdzie nie są mile widziane. Ponuro kiwa głową i bez słowa znika w ciemności.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s74",
        text: "Przez moment myślimy, że to koniec. Nasz ostatni błąd. Woda ciska nami o ściany szerokiego tunelu lub rury, która gwałtownie opada w dół. Nagle jednak podwodną ciszę zastępuje huk spadającej wody, zalewa nas światło dnia. Spadamy. Uderzenie w lustro wody boli, ale wysokość na szczęście nie okazała się dla nas zabójcza. Docieramy wpław do brzegu, przeklinając własną głupotę. Gdzie my u licha jesteśmy?",
        rule: "Odrzuć wszystkie żetony ze Stosu Znalezisk oprócz 2 wybranych. Wylosuj, zgodnie z zasadą Wyjścia z Kanałów, w którym z 3 Miejsc jesteście.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s75",
        text: "\"Oddaj wszystko, co masz, lub żegnaj się z życiem...\" Złodziej zabiera dobytek i powoli cofa ostrze. Ostrzega, by nie wykonywać żadnych gwałtownych ruchów.",
        rule: "Odrzuć wszystkie żetony ze Stosu Znalezisk.",
        show1: true,
        transText1: "Nie dam się okradać. Muszę dogonić tego złodzieja i odebrać, co moje",
        changeTo1: 92,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wystarczy, mam dość - WRÓĆ DO GRY"
    },
    {
        id: "s76",
        text: "Uff. Wąska półka wreszcie się kończy i tunel staje się szerszy. Znów możemy normalnie iść przed siebie.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s77",
        text: "Nasz towarzysz nie potrafi tego zrobić. Nikt z nas tego nie potrafi... Chowamy nóż i powoli odwracamy się w stronę wyjścia.",
        rule: "Dodaj 1 Nóż do Stosu Znalezisk.",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 27,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s78",
        text: "Przez chwilę czujemy się jak w teatrze cieni, a zaraz potem makabryczny spektakl dobiega końca. Jego aktorzy ulatniają się, zostawiając za sobą jedno martwe ciało.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s79",
        text: "Złodziej, w przeciwieństwie do nas, doskonale zna kanały. Jednak ich znajomość na niewiele mu się zdaje wobec długich nóg i rosnącej wściekłości naszego towarzysza. Nie lubi być okradany. Kiedy wraca z plecakiem, jego koszula jest mokra od krwi. \"Musiałem walczyć\" - mówi, ale woli nie wdawać się w szczegóły. A my wolimy nie pytać.",
        rule: "Przywróć skradzione żetony do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s80",
        text: "Wracamy. Gdy w schronieniu przemywamy ranę, dopiero wtedy widać, jak poważne było to skaleczenie...",
        rule: "Przerwij Eksplorację Kanałów.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s81",
        text: "Wykonujemy polecenia złodzieja. Rzucamy mu jeden z plecaków. Wciąż trzymając nóż na gardle naszego towarzysza, mężczyzna zabiera plecak i przewiesza go sobie przez ramię. \"Nie ruszajcie się\" - ostrzega. Po chwili wypuszcza naszego towarzysza, a sam znika w smolistej ciemności.",
        rule: "Odrzuć wszystkie żetony ze Stosu Znalezisk oprócz 2 wybranych.",
        show1: true,
        transText1: "Nie damy się okradać. Spróbujmy do dopaść",
        changeTo1: 61,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Najważniejsze, że nikt nie zginął... - WRÓĆ DO GRY"
    },
    {
        id: "s82",
        text: "\"Dobra, widzę, że nie dajesz się łatwo podejść i nie ufasz byle komu. To dobrze. Będzie z ciebie dobry żołnierz, jak się jeszcze trochę podszkolisz\" - odzywa się nagle towarzysz chłopaka. Poklepuje go po ramieniu i daje nam znak, że możemy odejść.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s83",
        text: "Przerażony szaleniec snuje się za nami, czasem coś bełkocze pod nosem. Cału czas z przerażeniem rozgląda się dookoła, a najczęściej za siebie...",
        rule: "Do końca tej Eksploracji Kanałów mężczyzna jest za nami. Jeden raz podczas tej wspólnej podróży możemy zdecydować, że to właśnie na niego zamiast na 1 z Postaci spadnie efekt pechowego wydarzenia (np. Rana, Choroba, itd.).",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s84",
        text: "Gdy wychodzimy, strach dzieci towarzyszy nam aż do wyloto z ich małego, zaśmieconego świata stworzonego przez wojnę.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s85",
        text: "Kamienie są śliskie i uciekają spod nóg. Wygląda na to, że okolica nad nami została zbombardowana podczas nalotu. Między kamieniami udaje nam się dostrzec kawałki malowanego we wzory tynku z jakiegoś mieszkania. Wykopujemy drogę na powierzchnię, ale nie jesteśmy wystarczająco ostrożni. W pewnym momencie zjeżdżamy w dół, a obsunięta cegła uderza jedno z nas w głowę, pozostawiając głęboką ranę. Wreszcie udaje nam się wydostać na zewnątrz obok przewróconego ramienia dźwigu.",
        rule: "Wybierz 1 z obecnych tu Postaci i podnieś jej rany o 1. Możesz natychmiast wyjść z Kanałów do dowolnego z 3 Miejsc.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s86",
        text: "Boban spluwa z dezaprobatą i opuszcza halę. Ruszamy dalej.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s87",
        text: "Nie zatrzymywał nas. Po chwili, szybkim krokiem, oddalaliśmy się od wyłomu prowadzącego do ruin linii tramwajowej.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s88",
        text: "",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią wybranej wcześniej Postaci.",
        show1: true,
        transText1: "Przy wyniku równym lub niższym",
        changeTo1: 77,
        show2: true,
        transText2: "Przy wyniku wyższym",
        changeTo2: 63,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s89",
        text: "W pośpiechu pochylamy się nad ciałami. obserwując z niepokojem wylot tunelu. Czujemy się jak hieny cmentarne, chociaż próbujemy się pocieszać, że zmarłym ich bagaże do niczego już się nie przydadzą. Marna pociecha. Zabieramy ze sobą wszystko, co zwraca naszą uwagę i co jesteśmy w stanie unieść. Gdy słyszymy szmer kroków gdzieś w ciemności przed nami, natychmiast wycofujemy sie, by poszukać innej drogi.",
        rule: "Dodaj 1 Konserwę, 4 Papierosy, 1 Uszkodzony Pistolet, 2x Biżuterię, 2 Części Elektryczne, 2 Części Mechaniczne, 2 Części Broni i 1 Nóż do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s90",
        text: "To był potworny moment. palce przez sekundę próbowały uczepić się śliskich kamieni, stopy bezskutecznie szukały oparcia. Przez kilka długich sekund czułeś, że ześlizgujesz się w dół i nagle już tylko bezwładny lot. Potworny ból został w końcu zduszony przez kotłującą się wode... Na zawsze.",
        rule: "Usuń z gry Postać, która spadła.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s91",
        text: "",
        rule: "Sara natychmiast przywiązała się do 1 Postaci (wybierz 1 z obecnych tu Postaci). Zapisz \"Sara, s91\" na Pustym żetonie. Połóż go przy karcie wybranej wcześniej Postaci. Od teraz żeton ten symbolizuje dziecko: SARA: \"Sara musi jeść (jak każda Postać)\" - za każdym razem, gdy Sara nie zostanie nakarmiona w fazie Zmierzchu, rzuć Czarną Kością. Wynik 1-5 = dziecko jest całkowicie wyczerpane i jest już za późno, by je ocalić - usuń z gry żeton Sary i patrz 661 w KSIĘDZE SKRYPTÓW. \"Dziecięca radość\" - pod naszym wpływem Sara zaczyna odżywać, a jej dobry nastrój okazuje się zaraźliwy. Tak długo jak Postać, przy której leży żeton Sary, jest w Schronieniu, Depresja żadnej z Postaci nigdy nie podniesie się powyżej 3 (nie dotyczy to tylko skryptu 1000 z KSIĘGI SKRYPTÓW).",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Przerwij Eksplorację Kanałów i WRÓĆ DO GRY"
    },
    {
        id: "s92",
        text: "Złodziej doskonale zna kanały. Jest jak cień. Odgłosy jego kroków raz wydają się bliskie, a za chwilę dalekie. Całkiem możliwe, że niedługo znowu wyskoczy z zasadzki. Lepiej zawrócić, póki nie jest jeszcze za późno.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s93",
        text: "Wycofujemy się aż do ostatniego rozwidlenia. Z ust nieznajomego wydobywa się westchnienie ulgi. Wyjaśnia przyciszonym głosem, że zaraz przy otwartej studzience znajduje się obóz żołnierzy zza rzeki. Zamontowali mikrofony, aby nasłuchiwać kroków. Mają granaty i likwidują kogo popadnie. Wyławiamy kilka informacji o granatach-pułapkach, zabójczych gazach, siedzibach przemytników i korytarzach zalanych ściekami. Opis kanałów w tej części miasta, jaki rysuje przed nami nieznajomy, nie napawa optymizmem. Na drugi raz będziemy o wiele bardziej uważać.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s94",
        text: "Błysk noża jest tak nagły, że nie zostawia mi żadnej szansy na reakcję. Napastnik przywykł do podobnych ataków. Właśnie teraz trzyma ostrze przy mojej szyi. Szare długie włosy opadają na pociągłą twarz. Czarne oczy są jak dwie dopalające się bryłki węgla. \"Dawaj, co masz, albo cię zabiję\" - ostrze nacina skórę przy szyi. To nie są żarty!",
        rule: "",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 75,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s95",
        text: "Przed sobą słyszymy odgłos odbezpieczanej broni. Przez stłuczony kineskop wystaje lufa karabinu, a z dziurawego materaca niewielki pistolet. \"To będzie tak, gołąbeczki... zostawicie, co macie, a my w zamian nie nafaszerujemy was ołowiem...\"",
        rule: "",
        show1: true,
        transText1: "Rzucamy się do ucieczki",
        changeTo1: 55,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zostawiamy wszystko i posłusznie wracamy skąd przyszliśmy - odrzuć wszystkie żetony ze Stosu Znalezisk i WRÓĆ DO GRY"
    },
    {
        id: "s96",
        text: "Ciemno i coraz zimniej. Idąc za znakiem, zapuszczamy się coraz dalej w nieznane i rzadko uczęszczane podziemia miasta. Nagły snop światła z pobocznego korytarza sprawia, że zamieramy w pół kroku. Oto mężczyzna w mundurze w pełnym rynsztunku patroluje kanały. Podobnych postaci jest więcej. Cienie trzech uzbrojonych mężczyzn poruszają się na ścianach, słyszymy przekleństwa i przyciszone rozmowy. Wygląda na to, że kogoś szukają, podążając dokładnie tą trasą, co my. Próbujemy wycofać się z tunelu, ale blade światło wojskowej latarki odcina nam jedyną drogę ucieczki.",
        rule: "Wylosuj 3 żetony Wrogów. Wszyscy żołnierze są uzbrojeni w Pistolety. Rozpocznij walkę - patrz Dziennik: STARCIE. Jeśli uda nam się zabić dwóch, trzeci ucieknie.",
        show1: true,
        transText1: "Po walce",
        changeTo1: 71,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s97",
        text: "Rezygnując w końcu ze słów, tłumaczymy gestami, by dzieciaki podążały za nami, a zaprowadzimy je do wyjścia. W końcu ruszyły. Nie przeszliśmy jednak nawet kilometra, gdy ciągnąca się nieco z tyłu trójka nagle znikła. W miejscu, gdzie jeszcze przed chwilą szły maluchy, dostrzegamy niewielkie, techniczne przejście, zdolne pomieścić co najwyżej dziecko. Słychać dochodzący z niego tupot małych stóp i płacz. Tylko tyle zaufania zostało w nich dla dorosłych ludzi.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s98",
        text: "Znowu jest wąsko i ciasno. Budząca klaustrofobię rura - bo ciężko ją nazwać korytarzem - wydaje się ciągnąć w nieskończoność. Skuleni brodzimy w półpłynnej masie nieczystości. Nagle słyszymy piskliwy głosik. Brzmi jak płacz maleńskiego dziecka. Po raz kolejny uświadamiamy sobie, że wojna nie daje szans najmłodszym. Płacz staje się coraz głośniejszy. Dochodzimy do rozwidlenia rur. Dostrzegamy przemykające pod ścianami szczury. Zbierają się na krawędzi światła, jakby wywęszyły coś godnego zainteresowania. Rozpaczliwe dźwięki dochodzą z bocznej, jeszcze ciaśniejszej odnogi.",
        rule: "",
        show1: true,
        transText1: "Idziemy w stronę płaczu",
        changeTo1: 141,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Nie mamy dość zapasów, by opiekować się jeszcze dzieckiem. Chodźmy dalej... - Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = podnieś Depresję danej Postaci o 1. WRÓĆ DO GRY"
    },
    {
        id: "s99",
        text: "Zza uchylonych drzwi jakiegoś technicznego pomieszczenia widzimy światło silnej latarki. Zaglądamy ostrożnie do środka. Mężczyzna o masywnej sylwetce siedzi przy ścianie, kryjąc twarz w dłoniach. Jego ciałem wstrząsają spazmy. Tuż obok na betonie leży hełm, a o ścianę jest oparty karabin szturmowy.",
        rule: "",
        show1: true,
        transText1: "Ukradkiem ruszamy dalej, próbując go ominąć",
        changeTo1: 130,
        show2: true,
        transText2: "Może warto mu pomóc? Podejdźmy bliżej",
        changeTo2: 187,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s100",
        text: "Jesteśmy już blisko miejsca, w którym będzie można wstać, gdy dogania nas fala przerażonych czymś gryzoni. Szczury przebiegają po nas, w panice drapiąc, gryząc i wchodząc pod ubrania. Na szczęście wystarczyło kilka ruchów i mogliśmy wstać, by zejść tej chmarze z drogi. Bydlaki gnają gdzieś dalej w tunel, a my - wystraszeni, ale cali - ruszamy w swoją stronę. Po chwili orientujemy się, że zgubiliśmy kilka rzeczy, ale nikt z nas nie chce wracać w głąb tunelu.",
        rule: "Odrzuć 1 dowolny żeton ze Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s101",
        text: "Wykładamy na mokrą posadzkę wszystko po kolei. Broń, jedzenie, cenne zapasy, które tak ciężko było zdobyć. Jeden z maruderów zarzuca sobie karabin naramię i podchodzi do nas. Wsadza rękę do naszych plecaków, obmacuje kieszenie, a my możemy tylko patrzeć w ciemne lufy i cicho kląć. Po wszystkim zostajemy w kanałach sami.",
        rule: "Odrzuć wszystkie żetony ze Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s102",
        text: "Najpierw słyszymy wycie. Kobiecy głos jest pełen żalu i bólu, aż ściska za serce. Kilkanaście kroków dalej widzimy ją. Idzie prosto na nas. Ma dwadzieścia kilka lat, ale brudna, wychudzona i z twarzą napuchniętą od płaczu wygląda bardziej jak stwór z koszmaru, a nie młoda dziewczyna. \"Chłopczyk, mały chłopczyk, widzieliście go?\" - głos jej drży. - \"Gdzieś tutaj był! Był tutaj! Tutaj, tutaj, tutaj!\" - krzyczy, jakby oszalała z żalu.",
        rule: "",
        show1: true,
        transText1: "\"Zgubiłaś syna? Gdzie go widziałaś? Pomóc ci go szukać?\"",
        changeTo1: 153,
        show2: true,
        transText2: "Nie da się jej już pomóc. Dziecko pewnie nie żyje, a ona bredzi",
        changeTo2: 215,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s103",
        text: "Pudło jest ciężkie, jakby były w nim kamienie. Skacząc z nim, jedno z nas zaupełnie straciło równowagę i chyba skręciło sobie kostkę. Teraz nie tylko niesiemy pakunek, ale musimy też pomóc towarzyszowi, bo każdy krok wywołuje ból. Odchodzimy w bezpieczne miejsce i zrywamy taśmę klejącą. Świecimy do środka i wyciągamy mniejsze opakowania z napisem... \"Klocki hamulcowe\". Tylko po to ryzykowaliśmy?",
        rule: "Rozdziel 1 Ranę pomiędzy obecne tu Postaci. Dodaj 2 Części Mechaniczne do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s104",
        text: "\"Tutaj jesteś! Do mnie!\". Z ciemności wypada siwy, zarośnięty mężczyzna z podłogową klepką uniesioną nad głowę. Niedźwiedź patrzy na niego łagodnie, a nieznajomy na nas - zdziwiony i przerażony. Po krótkim milczeniu mówimy mu, kim jesteśmy. On też dzieli się swoją historią. Nazywa się Nikolai i był treserem w cyrku. Kiedy wszyscy uciekli, a bomby zaczęły spadać, uciekł razem z niedźwiedziem do kanałów, świadom, że nie dotrze do swojej rodziny. W pewnej chwili spogląda na nas z nadzieją: \"A może... Może pomożecie nam uciec z miasta?\"",
        rule: "",
        show1: true,
        transText1: "Nie ma mowy! Nie będziemy łaźić po kanałach z takim towarzyszem",
        changeTo1: 123,
        show2: true,
        transText2: "Pomożemy mu - zwierze niczemu nie jest winne. Dość się już wycierpiało",
        changeTo2: 220,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s105",
        text: "Powietrze wyraźnie się poprawia. Na twarzach czujemy podmuch wiatru. Słychać też szum wody. Korytarz rozszerza się i wchodzimy do przestronnego pomieszczenia. Od razu rozpoznajemy to miejsce - to oddany tuż przed wybuchem wojny nowy kolektor biegnący pod rzeką. Miał zwiększyć przepustowość miejskiej kanalizacji. Teraz przedstawia opłakany widok. Całe pomieszczenie dosłownie zasłane jest trupami żołnierzy obu stron. Strategiczne przejście musiało stać się niedawno areną straszliwego starcia. Tylko bliskość powierzchni i rzeki powodują, że da się tu oddychać, choć słodki odór śmierci wywołuje mdłości. Po przeciwnej stronie widać zasypane wyjście. Pewnie dlatego teraz nikogo tu nie ma - kolektor nie przedstawia już żadnej wartości strategicznej. Wśród ciał dostrzegamy błyski metalu. Pewnie zwycięzcy przeoczyli kilka cennych przedmiotów.",
        rule: "",
        show1: true,
        transText1: "Ruszamy na poszukiwania",
        changeTo1: 161,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zostawmy zmarłych w spokoju. Czas iść - WRÓĆ DO GRY"
    },
    {
        id: "s106",
        text: "Jedno z nas zażywa przeterminowane leki.",
        rule: "Rzuć Czarną Kością za Postać, która to zrobiła.",
        show1: true,
        transText1: "Wynik 1",
        changeTo1: 229,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wynik 2-6 - leki są nieskuteczne, ale nie dzieje się też nic złego. WRÓĆ DO GRY | Wynik 7-10 - przeterminowane leki zadziałały normalnie (jak żeton Leków). WRÓĆ DO GRY."
    },
    {
        id: "s107",
        text: "\"Zanim wszystko się... No wiecie sami. Przed wojną byłem kanalarzem. Znam tu każdy zakręt.\" Nieznajomy ma na imię Toma. W grupie najwidoczniej poczuł się bezpieczniej, bo zaczyna o sobie opowiadać. \"Uciekłem pod ziemię, no mój blok ostrzelały czołgi, ale tu nie jest wcale lepiej. Wszystko mi ukradli! Dobrze, że nie zatłukli jak psa...\" Zawieramy z mężczyzną prosty układ - będziemy mu towarzyszyć w drodze na powierzchnię, a on opowie nam o nieznanych przejściach, ślepych zaułkach i podziemnych pomieszczenia.",
        rule: "Możesz natychmiast wyjść z Kanałów do dwolnego z 3 Miejsc. Zapisz \"Wskazówki Tomy, s107, I I I\" na Pustym żetonie i umieść go na Stosie Znalezisk. Traktuj go jak szary żeton o wadze 0 i wartości 0. Gdy skreślisz ostatnią kreskę, usuń ten żeton z gry. WSKAZÓWKI TOMY: W momencie dobierania karty Korytarza lub karty Pomieszczenia możesz skreślić 1 kreskę z żetonu, by dobrać 2 karty zamiast jednej, rozpatrzyć wybraną kartę, a drugą wtasować z powrotem do talii.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s108",
        text: "Znajdujemy go w wąskim tunelu technicznym na przewody. Siedzi z przestrzeloną na wylot i opadłą na piersi głową. W dłoni leżącej na podołku trup wciąż ściska mały pistolet. Podchodzimy bliżej i wtedy zauważamy obrzydliwe bąble, w których zastygła złocista ropa. Są wszędzie, na dłoniach, twarzy, karku...",
        rule: "",
        show1: true,
        transText1: "Lepiej nawet się do niego nie zbliżać. Przechodzimy dalej, wstrzymując oddechy",
        changeTo1: 162,
        show2: true,
        transText2: "Takiej okazji nie można przegapić. Jedno z nas zabiera pistolet i idziemy dalej - wybierz 1 z obecnych tu Postaci",
        changeTo2: 216,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s109",
        text: "Żegnamy się z kobietą, wycofujemy i układamy na miejscu część zwalonych cegieł. Potem zaczynamy myszkować po pobliskich korytarzach. W jednym z nich ewidentnie śmierdzi trupem. Ślepa odnoga kończy się niewielkim pomieszczeniem, w którym smród jest nie do wytrzymania. Na podłodze znajduje się prymitywne palenisko, duży otłuszczony gar i trochę sztućców. Dopiero po chwili dostrzegamy, co leży z tyłu. To sterta pożółkłych kości oraz czaszek. Z trudem opanowujemy mdłości uświadomiwszy sobie, jaki sposób na przeżycie znalazła Marina. Czas podjąć jakąś decyzję...",
        rule: "",
        show1: true,
        transText1: "Musimy uwolnić dzieci",
        changeTo1: 230,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Nie możemy wziąć na siebie opieki nad trójką dzieci. Odchodzimy, zostawiając maluchy z ich \"opiekunką\" - rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = podnieś Depresję danej Postaci o 1. WRÓĆ DO GRY"
    },
    {
        id: "s110",
        text: "Dosiadamy się do opuszczonego obozowiska i łakomie wyjadamy stare mięso. Na górze wciąż jest zimne, a na dole zdążyło się już zwęglić. Każdy szmer w pustym korytarzu sprawia, że jego kawałki stają nam w gardle. Mija kilka minut i nic się nie dzieje. Zostawiamy wciąż tlące się drewienke, pustą puszkę i odchodzimy, zanim ktoś przyłapie nas na kradzieży.",
        rule: "Obniż Głód wszystkich obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s111",
        text: "Idziemy ostrożnie, gdy nagle słyszymy złowieszcze szczęknięcie. Jedno z nas nadepnęło na zapalnik miny. Zamieramy w bezruchu, ale wiemy że dla naszego towarzysza nie ma już ratunku. Łzy ciekną nam po twarzach - jednocześnie chcemy się z nim pożegnać i boimy wykonać choćby kroku. Aż dziwne, że zwnosi to tak dobrze... Ostrożnie oddaje nam wszystkie swoje rzeczy. Wycofujemy się po kilku śladach i ruszamy w głąb korytarza, byle dalej od tego miejsca. Kilka chwil później słyszymy eksplozję, a korytarz wypełnia się pyłem. Straciliśmy właśnie kolejnego przyjaciela...",
        rule: "Usuń z gry Postać, która nadepnęła na minę. Podnieś Depresję wszystkich obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s112",
        text: "Rozchodzimy się po parkingu, na siłę otwierając bagażniki i rozbijając szyby. Któreś z nas wyciąga nawet jednego z pasażerów ze środka jakiejś limuzyny, byle tylko dostać się do porzuconej torebki. Zwęglony trup uderza o beton z głuchym łoskotem. Wszędzie wokół podnoszą się coraz gęstsze tumany sadzy.",
        rule: "Dodaj do Stosu Znalezisk 1 wybrany żeton za każdą z obecnych to Postaci. Możesz wybrać każdy żeton więcej niż raz: Biżuteria, Część Elektryczna, Część Mechaniczna, Książka, Opatrunek, Papieros.",
        show1: true,
        transText1: "Może warto poszukać drogi na zewnątrz? W końcu musiało być tu jakieś wyjście ewakuacyjne",
        changeTo1: 138,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zaraz nie będzie tu czym oddychać. Zresztą dość już zabraliśmy. Czas się zwijać - WRÓĆ DO GRY"
    },
    {
        id: "s",
        text: "",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },

];

// {
//     id: "s31",
//     text: "",
//     rule: "",
//     show1: false,
//     transText1: "",
//     changeTo1: 0,
//     show2: false,
//     transText2: "",
//     changeTo2: 0,
//     show3: false,
//     transText3: "",
//     changeTo3: 0,
//     reset: "WRÓĆ DO GRY"
// },
