module.exports = [
    {
        id: "s1",
        text: "Nie dla wszystkich śmierć na wojnie okazuje się szybka. Żołnierz, którego mamy przed sobą, leży w niewielkim, zaśmieconym pomieszczeniu na porzuconych noszach. Jego mundur jest przepocony, chociaż wokół panuje zimno. Podchodzimy bliżej. Mężczyzna krztusi się własną krwią, jedną ręką dociskając prowizoryczny opatrunek. Wie, że jego chwile są policzone, ale nie ma odwagi i sił, by sam ze sobą skończyć. Drżącą dłonią podaje nam nóż i prosi, abyśmy przynieśli mu ulgę.",
        rule: "",
        show1: true,
        transText1: "Spełnijmy jego prośbę - WYBIERZ 1 Z OBECNYCH TU POSTACI ",
        changeTo1: 88,
        show2: true,
        transText2: "Spróbujmy mu pomóc. Może coś da się jeszcze zrobić",
        changeTo2: 56,
        show3: true,
        transText3: "Zostawmy go. Nie możemy mu pomóc ani nie chcemy mieć jego krwi na rękach",
        changeTo3: 27,
        reset: ""
    },
    {
        id: "s2",
        text: "Ta część kanałów wydaje się starsza od reszty. Idziemy niemal po omacku, opierając się rękoma o kamienne ściany. Wąski chodnik prowadzi wzdłuż szerokiego zbiornika ścieków. Kamień jest tu zmurszały i osuwa się spod stóp. \"Plum!\" Mija chwila, nim słyszymy odgłos uderzenia kawałka cegły o lustro zmętniałej wody. Jeden nieostrożny ruch i my też spadniemy w dół.",
        rule: "",
        show1: true,
        transText1: "Spróbujmy przejść",
        changeTo1: 62,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Ta droga jest zbyt niebezpieczna, lepiej kończmy na dziś i wracajmy do schronienia - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY"
    },
    {
        id: "s3",
        text: "Przemycanie papierosów przez oblężone miasto to dla Bobana chleb powszedni. Mężczyzna trafił na nas w ciemnym kanale. Ma zniszczoną nałogiem twarz i krótko ścięte włosy. Szczerbaty uśmiech nie należy do sympatycznych i podobno jest efektem jakiejś nieuczciwej transakcji. Wypchane papierosami kieszenie często powodują problemy, ale Boban nie zna innego życia. Wszędzie nosi ze sobą broń, święcie wierząc, że jeśli sprawy nie rozwiąże \"fajka pokoju\", to zawsze pozostaje niezawodna kula. \"W czasie wojny szmuglowałem, no to co miałbym w czasie wojny robić? Macie szczęście, że wam generał wszystkich faj nie wykupił. Ja mam najlepsze w mieście, no i taniej się nie da\" - mówi z dumą, prezentując resztki swojego towaru.",
        rule: "Możemy kupić od niego paczkę papierosów (patrz Dziennik: HANDEL) za żetony o wartości 5. Prowizja: 0. PACZKA PAPIEROSÓW: Zapisz \"Paczka Papierosów, s3, I I I\" na Pustym żetonie i połóż go na Stosie Znalezisk. Traktuj go jak zielony żeton o wartości 6 za każdą kreskę i wadze 0. W dowolnym momencie możesz skreślić 1 kreskę, aby dodać 6 żetonów Papierosów. Gdy skreślisz ostatnią kreskę, usuń ten żeton z gry.",
        show1: true,
        transText1: "Jeśli kupiliśmy paczkę papierosów",
        changeTo1: 68,
        show2: true,
        transText2: "Jeśli nie",
        changeTo2: 86,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s4",
        text: "Echa głosów niosą się po sklepieniach kanału na moment przed tym, jak dostrzegamy ludzkie cienie. Ton głosu już z dala sugeruje kłótnię. Chwilę później zaczynamy rozpoznawać poszczególne słowa: \"Mówiliście, że to blisko, a idziemy już godzinę\" - skarży się niska postać. Po cieniu na ścianie orientujemy się, że nieznajomy energicznie gestykuluje, jakby rozważał, czy nie przebiec w przeciwną stronę. \"Trzeba było naokoło, ale teraz do wyjścia z miasta niedaleko, pan zobaczy\" - zgarbiony czarny kontur pojawia się w mdłym świetle latarki trzeciej postaci. \"Oby! Pamiętajcie ile wam zapłaciłem. Dam drugie tyle, jeśli wyprowadzicie mnie stąd żywego\" - odpowiada mikrus. \"Zaraz zobaczymy, czy aż tyle masz. Andrej, kończmy z nim!\" - odzywa się trzeci głos. Jego cień rośnie nagle i zupełnie zakrywa dwie pozostałe postacie. Słyszymy rwany krzyk.",
        rule: "",
        show1: true,
        transText1: "Biegniemy na pomoc ofierze",
        changeTo1: 53,
        show2: true,
        transText2: "Lepiej nie kusić losu",
        changeTo2: 78,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s5",
        text: "Dwa kartony książek - tylko tyle i aż tyle udało mu się uratować i zabrać do kanału. Mężczyzna, którego mamy przed sobą, ma poparzone, grube dłonie. Był ochroniarzem w bibliotece. Gdy spadły bomby i ogień pochłaniał budynek, zaczął wynosić z zaplecza wszystko, co wpadło mu w rękę. \"I na co mi to wszystko? Przecież teraz nikt tego nie będzie czytał. Było iść do żony, gdy zaczęło się bombardowanie, może bym zdążył chociaż do małej, nim umarła. Może, gdybym mógł cofnąć czas...\" Przyglądamy się budzącej żal postaci, która wolała ratować książki niż własną rodzinę.",
        rule: "",
        show1: true,
        transText1: "\"Czasu nie cofniemy, ale może te książki będą miały wartość dla potomnych. Mógłbyś przenieść je w bezpieczne miejsce\"",
        changeTo1: 65,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zostawmy go z jego zmartwieniami. To nie nasz problem - WRÓĆ DO GRY"
    },
    {
        id: "s6",
        text: "Od dłuższego czasu czujemy się obserwowani. W szparach między cegłami dostrzegamy zarys niskiej postaci. Wygląda na to, że ktoś podąża naszym śladem, korzystając z równoległego korytarza. Wyraźnie słyszymy towarzyszące nam kroki - powolne i ciche. Ktokolwiek za nami idzie, nie zamierza się ujawnić",
        rule: "",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 60,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s7",
        text: "W środkowej części kanałów natrafiamy na zamaskowany gruzami kabel telefoniczny. W zamierzeniu miał łączyć dowództwo garnizonu w śródmieściu z ogniskami oporu za rzeką. Nie udało się. Połączenie zostało wedle plotek przerwane przez sabotażystę, którego ciało być może mamy właśnie przez sobą. Do mężczyzny strzelano kilkakrotnie z bliska, zupełnie jak do tarczy treningowej. Dookoła ciał jest jednak więcej. Zaścielają cały korytarz. Mundury łącznościowców, sanitariuszy, żołnierzy. Mundury obu stron, wszyscy tak samo martwi, ograbieni ze wszystkiego, co miało jakąkolwiek wartość. Przechodzimy obok nieruchomych zwłok i zamykamy im otwarte oczy. Przynajmniej tyle możemy zrobić - zdobyć się na ostatni ludzki gest.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s8",
        text: "W wąskim przejściu udaje nam się wypatrzyć jakiś ruch. Mężczyzna ubrany w wełniany płaszcz zaklinował się w ciasnym tunelu. Chciał przepchnąć się przez szczelinę z całym plecakiem i niewiele brakowało, aby ten pomysł okupił życiem. Wspólnymi siłami wyswabadzamy mężczyznę z pułapki. Jego podziękowaniom nie ma końca. Dzieli się z nami wyjętym z plecaka chlebem i opowiada, że wraz z bratem, Petarem, ledwie uratował się z pogromu swojej rodzinnej wsi. Obaj próbowali przedrzeć się do miasta przez kanały. Jego brat musiał gdzieś zabłądzić, ale chłopak nie traci nadziei, że uda mu się go odszukać. Instruujemy go, jak przebyć drogę, którą sami tu dotarliśmy, by wydostać się do bezpieczniejszej części miasta. Po chwili po mężczyźnie pozostało już tylko wspomnienie. Ruszamy dalej.",
        rule: "Obniż Głód 1 z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s9",
        text: "Ciemny, śmierdzący tunel kończy się zawaloną ścian, przez którą bez trudu przedostajemy się do niewielkiego pomieszczenia. Oprócz śmieci leży tu kilka zawilgoconych książek i pokryte kurzem figurki świętych. Nie jesteśmy tu jednak sami. Troje zmarźniętych dzieci tuli się do siebie w kącie pokoju. Patrzą na nas jak na potwory, a przerażenie w ich oczach jest nieopisywalne. Nie odpowiadają na żadne pytanie, zupełnie tak, jakby nie rozumiały ani jednego naszego słowa. Co z nimi zrobić?",
        rule: "",
        show1: true,
        transText1: "Ruszajmy dalej. Nie uratujemy wszystkich sierot, choćbyśmy chcieli",
        changeTo1: 84,
        show2: true,
        transText2: "Spróbujmy przekonać dzieci, by ruszyły z nami do wyjścia. Może ktoś na zawnątrz się nimi zaopiekuje",
        changeTo2: 97,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s10",
        text: "Kolektor ma szerokość zaledwie metra, ale o dziwo jest suchy. Czołgamy się uważając, by nie zablokować się w ciasnym przejściu. Droga przed nami zakręca i nagle zaczyna opadać. Przedtem był to najwyraźniej tunel regulujący poziom ścieków, teraz są to raczej śliskie schody z nadzwyczaj niskim stropem. Powoli schodzimy w dół, modląc się, aby tunel nie okazał się ślepą odnogą. Ciche modlitwy tym razem zostają wysłuchane. Udaje nam się bez szwanku pokonać wąski wylot na dole... ale przeciskając się wąskim przejściem uszkadzamy jeden z plecaków. Dopiero po jakimś czasie orientujemy się, że przez nową dziurę w plecaku co nieco wypadło i utonęło gdzieś za nami w brudnym szlamie.",
        rule: "Odrzuć dowolne 3 żetony ze Stosu Znalezisk (jeśli jest ich mniej, odrzuć wszystkie).",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s11",
        text: "Słyszeliśmy, że ten kolektor jest bezpieczniejszy od reszty, ale nasze informacje okazują się przedawnione. Schodzimy w dół cementowej studni, zatykając szmatami nosy. Miało być płytko, ale nie jest. Dołem płynie obrzydliwa, żółtawa maź. Stoimy w niej po kolana, rozglądając się na boki. Nic, wszędzie ciemność. Kanał wygląda na niedawno zalany - przed sobą dostrzegamy zarys jakiejś prowizorycznej zapory.",
        rule: "",
        show1: true,
        transText1: "Spróbujemy sforsować przeszkodę",
        changeTo1: 51,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wybór tej drogi nie był dobrym pomysłem. Wracajmy do domu, na dziś wystarczy - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY."
    },
    {
        id: "s12",
        text: "",
        rule: "",
        show1: true,
        transText1: "JEŚLI W TEJ EKSPLORACJI KANAŁÓW BIERZE UDZIAŁ TYLKO 1 POSTAĆ",
        changeTo1: 94,
        show2: true,
        transText2: "JEŚLI WIĘCEJ - WYBIERZ 1 Z OBECNYCH TU POSTACI",
        changeTo2: 54,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s13",
        text: "Jest tak ciemno, że czujemy się niemal jak ślepcy, wymacując słabym promieniem niczym białą laską fragmenty drogi tuż przed sobą. Brodzimy po kolana w mętnej wodzie, gdy nagle dostrzegamy w oddali światło uchylonej studzienki kanalizacyjnej. I ruch tuż przed nami... ktoś się zbliża! Mężczyzna przytrzymuje przy ustach palec, w jego oczach widzimy lęk. Daje nam ręką znak, abyśmy natychmiast się wycofali. Wygląda, jakby bał się, że ktoś go usłyszy... Dookoła jednak nikogo nie ma. Czyżbyśmy trafili na kolejnego szaleńca?",
        rule: "",
        show1: true,
        transText1: "Wycofajmy się. Potem będzie czas na zadawanie pytań",
        changeTo1: 93,
        show2: true,
        transText2: "Pytamy, co tak bardzo go przestraszyło",
        changeTo2: 66,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s14",
        text: "Ta część kanałów rzadko jest odwiedzana przez żywych. Czarne ściany tunelu i leżące w wodzie zwęglone ubrania przypominają o tym, co kiedyś tu zaszło. Gdy trwała ewakuacja dzielnicy, żołnierze zza rzeki w okrutny sposób postanowili rozprawić się z partyzantami. Wpompowali do kanałów benzynę, którą następnie podpalili. W milczeniu przechodzimy przez pomieszczenie pełne szczątków poległych, starając się nie patrzeć na mijane ciała.",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = zapisz \"Lęk, s14\" na Pustym żetonie i połóż go na karcie danej Postaci. Od teraz aż do końca Kampanii, za każdym razem gdy dana Postać weźmie udział w Eksploracji Kanałów, podnieś jej Depresję o 1. Przy wyniku wyższym = nic się nie dzieje.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s15",
        text: "Najpierw musieliśmy przygarbić plecy, potem poruszać się na czworaka. Teraz czołgamy się pod coraz niższym sklepieniem wąskiego tunelu. Umysł płata figle i zdaje nam się, że jest już zbyt ciasno, by swobodnie zaczerpnąć tchu. Pora zadać sobie pytanie, czy pełzniemy dalej, czy lepiej w tym momencie zrezygnować i wrócić.",
        rule: "",
        show1: true,
        transText1: "Zaszliśmy już za daleko, by teraz rezygnować",
        changeTo1: 57,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wracamy - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY."
    },
    {
        id: "s16",
        text: "Butelki... Wszędzie walają się rozbite butelki. Stąpamy po kawałkach strzaskanego szkła, zaścielając małe pomieszczenie. Ktoś tu pomieszkiwał. Brudne szmaty pachną mocnym alkoholem i ledwie wyczuwalną wonią papierosów. W zagłębieniu przy rurze udaje nam się wymacać skórzany portfel z plikiem podrobionych paszportów, wyrabianych zapewne przez fałszerza. Musiał być dobry w swoim fachu. I drogi. Przy swojej poduszce trzyma prawdziwy skarb. Przednie whiskey, za które wielu byłoby gotowych zabić. Taka butelka nie może się zmarnować!",
        rule: "Zapisz \"Whiskey, s16\" na Pustym żetonie i połóż go na Stosie Znalezisk. Traktuj go jak zielony żeton o wartości 30 i wadze 1. Ponadto w dowolnym momencie możesz użyć Whiskey identycznie jak Spirytusu",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s17",
        text: "Odgłosy naszych kroków wystarczyły, by napędzić stracha żyjącemu w kanałach biedakowi. Mężczyzna już z daleka unosi ręce w górę, słabym głosem błagając o zmiłowanie. Podchodzimy bliżej. Był torturowany. Skóra na jego policzkach wygląda tak, jakby ktoś przystawił do niej rozgrzane żelazko. Nieznajomy kuli się pod ścianą, biorąc nas za swoich oprawców. Nieśmiało unosi ku nam rozbiegany wzrok, sunąc dłonią po spieczonym policzku. \"Ja nie chcę tam wracać, do nich... oni... oni...\" - biedak bełkocze niewyraźnie. Widzimy, że ten człowiek przeszedł przez horror, który kosztował go zbyt wiele, i jego umysł się poddał. Teraz zachowuje się jak kilkuletnie dziecko, rozglądające się w obawie przed kryjącymi się w każdym zakamarku potworami.",
        rule: "",
        show1: true,
        transText1: "Pozwalamy mu wędrować z nami aż do wyjścia z kanałów",
        changeTo1: 83,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "\"Bo zaprowadzimy cię z powrotem do nich!\" Pozbywamy się jego towarzystwa, posuwając się do gróźb. WRÓĆ DO GRY "
    },
    {
        id: "s18",
        text: "Płacz, śmiech, złorzeczenia. Trzy dostarczone listy i trzy róźne reakcje odbiorców. Trudno wymazać z pamięci zrozpaczoną twarz matki, kiedy odbierała od nas list informujący o śmierci jej syna... Wciąż słyszymy w myślach śmiech ulgi na wieść o tym, że dziewczyna żyje, a co więcej, wciąż wierzy w swoje ślubne plany... Wzdrygamy się na wspomnienie, jak kobieta miotała w naszą stronę wiązanki przekleństw, a potem wycelowała broń i odbezpieczyła ją. Kazała nam się wynosić i nie chciała nawet słyszeć o liście od kogoś, kogo najwyraźniej wolała uznać za zmarłego. To tylko trzy fragmenty czyjegoś życia przerwanego przez wojnę.",
        rule: "Usuń żeton Listów z gry. Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = obniż Depresję danej Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s19",
        text: "Sylwetki uzbrojonych postaci stojących obok barykady wyraźnie odcinają się od mroku wielkiej hali. Mężczyźni i kobiety wydają się celować w naszą stronę. W pierwszej chwili chcemy zerwać się do ucieczki, dopiero potem przychodzi refleksja. Nikt nas nie ściga, nie krzyczy, nie strzela. Nikt się nie rusza... Podchodzimy bliżej nieruchomych postaci, czując, jak z każdym krokiem włosy coraz bardziej jeżą nam sie na głowie. Mówiono nam o prtyzantach wykorzystujących w lesie kukły żołnierzy, aby w ten sposób odstraszyć wroga, jednak nigdy nie słyszeliśmy, aby używano w tym celu prawdziwych ciał. Martwych oparto o ściany z pomocą desek i przyczepiono im atrapy broni, najwyraźniej licząc, że widoczne z oddali sylwetki wystarczą, by przegnać stąd intruzów. Ruszamy dalej.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s20",
        text: "Przemierzamy labirynt kolektorów i docieramy do wysuszonego kanału. Zardzewiała drabinka prowadzi wysoko w górę, w stronę krat kanalizacyjnych. Zaczynamy się wspinać i natychmiast przestajemy, keidy na nasze głowy spadają drobiny papierosowego popiołu. Ktoś jest nad nami, na ulicy. Dwie ciemne sylwetki majaczą zaraz nad kratką ściekową. Ich rozmowę zagłusza warkot silnika i wypowiadany ostrym tonem rozkaz zatrzymania pojazdu. Serca biją nam szybciej... Wygląda na to, że dotarliśmy pod jakiś odległy posterunek kontrolny. \"Co przewozicie? Ach, jedzenie - mówicie? A to pod plandeką to też jest jedzenie?\" - słyszymy głos, a zaraz potem odgłosy szamotaniny i dwa głuche wystrzały. Padające ciała zasłaniają nam widok. Gdy rozlega się kolejny strzał, z przerażeniem widzimy, jak kula przeszywa leżące ciało i rykoszetem odbija się w studzience, w której tkwimy. Spadają na nas pierwsze krople krwi. Najciszej, jak potrafimy, schodzimy na dół i ruszamy dalej...",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = podnieś Depresję danej Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s21",
        text: "Jest tu zimno i mokro, a w powietrzu czuć wyraźny zapach stęchlizny i wilgoci. Nagle dołącza się inny zapach... zapach pieczonego mięsa! Zaburczało nam w brzuchach i ślina podbiegła pod języki. W jednym z niewielkich, technicznych pomieszczeń dostrzegamy tlący się żar. Ktoś tu niedawno był. Na niedopalonych do końca kawałkach drewna zostały kawałki niedojedzonego mięsa. Trzeba wyciągać szybko, bo się spalą. Tylko że to... pieczone szczury.",
        rule: "",
        show1: true,
        transText1: "Częstujemy się. Głodny człowiek nie wybrzydza",
        changeTo1: 58,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Nie ryzykujemy, mięso może być zatrute - WRÓĆ DO GRY"
    },
    {
        id: "s22",
        text: "Wojna dotarła do kanałów już dawno, ale nigdy nie dawała tak silnie o sobie znać... Z bocznych korytarzy kanałów wychodzą żołnierze w pełnym rynsztunku. W oddali słyszymy odgłosy wystrzałów. To ludzie broniący bariery błagają o wsparcie, próbując odeprzeć nieoczekiwany atak zza rzeki. W ciemności każdy strzał jest widoczny jak wystrzelona w nocy raca. \"Nie widzimy ich! Gdzie oni są?! Dawajcie wsparcie! Słyszycie?! Oni zaraz będą w mieście!\" - echem niosą się wściekłe krzyki radiowca. Jakiś żołnierz zagradza nam przejście. Pyta o dokumenty, których nie mamy, i ostrym tonem odsyła nas z powrotem. To koniec na dziś, trzeba wracać, utro możemy poszukać podziemnej drogi do innej części miasta.",
        rule: "Przerwij Eksplorację Kanałów.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s23",
        text: "Owalny, zabytkowy tunel, którym idziemy, służył dawniej jako zbiornik na wodę. Nad sobą słyszymy odgłosy tłoków i po chwili docieramy do wciąż czynnej stacji pomp położonej na przedmieściach. Przez kratę ściekową w podłodze dostrzegamy pomieszczenie położone jeszcze głębiej, pod nami. A także krążących po nim ponurych żołnierzy. Są podenerwowani i byle szelest wystarczy, aby sięgneli po broń. \"Ilu ich jest?\" - pyta jeden z nich. W drzwiach pojawia się młody chłopak, odziany w mundur i uzbrojony w bagnet. \"Jelena naliczyła pięciu w głównej hali i dwóch w śluzie. Może ich być jeszcze więcej, mogą być gdziś blisko...\" - odpowiada i nagle wybałusza oczy, potyka się i pada, a po posadzce rozlewa się plama krwi. Ktoś rozbija lampę i pomieszczenie spowija całkowita ciemność. Nagle rozlegają się strzały, a w urywanym blasku dostrzegamy ciemne sylwetki, noże i błyszczące lufy. Żołnierz, którego obserwowaliśmy, pada raniony serią z broni automatycznej. Zaczęło się. Mamy chwilę, by wycofać się głębiej do podziemnych tuneli. Wolimy nawet nie myśleć, co stanie się, jeśli któraś ze stron przejmie pełną kontrolę nad wodą w mieście.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s24",
        text: "Ciasny tunel przed nami można pokonać jedynie na czworakach. Najpierw zapuszczamy się na rekonesans i po kilku metrach gwałtownie przystajemy. Po drugiej stronie przejścia jarzy się blade światło, najpewniej pochodzące z latarki. Nagle światło zaczyna mrugać i po chwili gaśnie. Poza popiskiwaniem głodnych szczurów nie słyszymy wokół żadnych innych odgłosów. Ludzi, szumu wody. Nic.",
        rule: "",
        show1: true,
        transText1: "Ktokolwiek jest po drugiej stronie, na razie nie zdradza złych zamiarów. Idźmy dalej.",
        changeTo1: 67,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zawracajmy. To może być jakaś pułapka - PRZERWIJ EKSPLORACJĘ KANAŁÓW I WRÓĆ DO GRY"
    },
    {
        id: "s25",
        text: "Przekreślone koło to symbol, który od jakiegoś czasu towarzyszy naszym krokom. Namalowany kredą na ścianie być może do niedawna służył do oznaczania bezpiecznej drogi dla uchodźców albo pomagał nie zgubić się w ciemności ich katom. Nie dowiemy się tego, jeśli sami nie sprawdzimy. Tylko czy warto ryzykować?",
        rule: "",
        show1: true,
        transText1: "Sprawdźmy, gdzie może doprowadzić nas ten znak",
        changeTo1: 96,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wybierzmy inną drogę - WRÓĆ DO GRY"
    },
    {
        id: "s26",
        text: "Tunel zakręt, tunel i ani się obejrzymy, a wracamy do tego samego rozwidlenia korytarzy. Błądzimy tak już dobre kilka godzin. Próbujemy wybrać inną drogę, oznaczając naszą trasę znalezionym kawałkiem cegły, ale skutek jest zawsze podobny. W ciemności tracimy poczucie czasu. Byle szmer bierzemy za odgłos ludzkich stóp, choć za jedynych towarzyszy mamy wygłodniałe szczury. Wychodzimy w następny ślepy korytarz. Pozornie. W kratach zieje wyrwa umożliwiająca nam przejście na drugą stronę. Nareszcie! Z ulgą dostrzegamy odsłoniętą pokrywę włazu kanalizacji i wpadające przez nią blade światło słońca.",
        rule: "Podnieś Zmęczenie dowolnej z obecnych tu Postaci o 1. Po wyjściu z Kanałów zaczniesz z 2 kartami Przeszukiwania mniej w talii Nieznanego. Możesz natychmiast wyjść z Kanałów do dowolnego z 3 Miejsc",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s27",
        text: "Jęki rannego słyszymy znacznie dłużej, niż to możliwe. Gdy zdajemy sobie sprawę, że to już tylko nasze złudzenie, w końcu cichną.",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = podnieś Depresję danej Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s28",
        text: "Podchodzimy do ściany niewielkiego pomieszczenia. Ściek spływa tu prosto do położonego na przedmieściach jeziora, nad którym dawniej co weekend ludzie wypoczywali po trudach tygodnia. Teraz ten \"raj\" z przesłości jest zupełnie niedostępny, mimo że oddzielają nas od niego jedynie kraty i zmętniała woda. W jej odbiciu dostrzegamy poruszające się białe chmury, cięte śladami odrzutowych samolotów. Las na drugim brzegu wygląda na nietknięty wojną, w przeciwieństwie do piętrzących się po prawej, dymiących ruin dzielnicy willowej. Biurowce na wschodzie będą następne. Jak na zwolnionym filmie, obserwujemy otwierające się klapy samolotów i wypluwane przez nie bomby. W wodnej taflii odbijają się wszystkie odcienie czerwieni. Z rezygnacją odwracamy wzrok i wracamy z powrotem do tunelu. Do naszego własnego piekła.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s29",
        text: "Kobieta leży przysypana, tylko część głowy wystaje spod gruzu. Po śladach na skórze wnioskujemy, że umarła kilka dni temu. Na na sobie szary mundur. Przypięty na piersi znak świadczyo tym, że należała do rebeliantów. Spluwamy na ziemię. \"My\" czy \"oni\" przestało już mieć znaczenie. Kto ma broń, ten zabija, po prostu. Przy jej ciele znajdujemy torbę wypełnioną listami.",
        rule: "",
        show1: true,
        transText1: "Rozdzieramy listy i przeglądamy",
        changeTo1: 59,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Rzucamy je w błoto i idziemy dalej - WRÓĆ DO GRY"
    },
    {
        id: "s30",
        text: "Wąska kładka prowadzi nad podziemnym zbiornikiem ścieków. W oddali widzimy dwie szamoczące się sylwetki. Barczyści mężczyźni w mundurach ociekają krwią i szlamem. Jeden z nich uderza przeciwnika w brzuch, posyłając go na krawędź kanału. \"Wybrałeś złą stronę, bracie. Powinniśmy się trzymać razem\" - mówi z triumfem. Głowa jego ofiary zwisa w dół przepaści. Jeszcze chwila i mężczyzna runie w dół. \"Święta racja, bracie, powinniśmy być razem\" - odpowiada tamten cicho. Resztkami sił mocno chwyta przeciwnika za ramiona i ciągnie go ze sobą. Guchy odgłos upadku odbija się od ścian, a chwilę później dwa bezwładne ciała kołyszą się w czarnej wodzie pod nami.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s31",
        text: "Czołgamy się przez ciasny tunel techniczny, uważając na biegnące obok kable, choć pewnie prąd od dawna juz w nich nie płynie. Od metalowych ścian odbija się szum wody, a także bardziej niepokojący dźwięk. Cichy płacz dziecka dobie gdzieś spod podłogi i staje się głośniejszy w miarę jak nasz korytarz zaczyna zakręcać. Mamy nadzieję, że uda nam się znaleźć porzucone w tunelu dziecko, ale nasz korytarz odbija w lewo - oddalamy się coraz bardziej i bardziej od źródła płaczu, prowadzeni przez nieubłagany labirynt przejść. Zaciskamy zęby w bezsilnej rezygnacji - nie możemy nic zrobić, żeby pomóc porzuconemu malcowi.",
        rule: "Podnieś Depresję 1 z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s32",
        text: "Niektóre dzielnice broniły się dłużej, niż wszyscy sądzili. W brudnym szlamie natrafiamy na upchane do zapleśniałej torby fragmenty relacji z odwrotu jakiejś walczącej grupy. \"Cegielnia stracona. Dostaliśmy z dowództwa rozkaz, by przebić się do centrum. Zeszliśmy do kanałów z oddziałem Petrovicia. Żeby dojść do miejsca przeznaczenia, musieliśmy przeprawić się przez zalany kolektor. Przejście kilometra w gęstym szlamie zajęło trzy godziny. Pomagaliśmy sobie długimi drążkami, żeby utrzymać się na powierzchni. Nie było łatwo. Od wyziewów kilku naszych dopadły halucynacje. Zostawiliśmy ich za sobą. Nie oglądaliśmy się do tyłu. Szliśmy dalej. Aż do tego miejsca. Za nami wróg. Przed nami koniec korytarzy. Wygląda na to, że dotarliśmy już do kresu.\"",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s33",
        text: "W ścianie kanału zieje wyłom, przez który dostrzegamy fragmenty biegnących torów niedokończonego, podziemnego tramwaju. Obok spoczywa porzucony sprzęt budowlany. Srebrne wiertła i uśpione buldożery. Jeden z nich budzi się nagle, jasny blask pada prosto na nas. \"Wi... wi... widzieliście tam kogo?\" - łysy żołnierz wspierający się na kulach wyłania się z kabiny pojazdu. Wygląda na przerażonego. Czyżby był tutaj sam?",
        rule: "",
        show1: true,
        transText1: "Odejdźmy, zanim wezwie posiłki",
        changeTo1: 87,
        show2: true,
        transText2: "Zachowujmy się spokojnie i porozmawiajmy z nim",
        changeTo2: 52,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s34",
        text: "Zaglądamy do tego pomieszczenia i przecieramy oczy ze zdumienia. Niewielkie, szaro-białe grzyby pokrywają kilka rzędów półek. To pieczarkarnia! Ktoś hoduje tu grzyby, dba o uprawę. I ma pecha, bo właśnie znaleźliśmy jego skarb. Trudził się, ale z efektów skorzysta ktoś inny.",
        rule: "",
        show1: true,
        transText1: "Pakujemy do plecaków, ile się da",
        changeTo1: 70,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Wychodzimy. Ktoś włożył w to za dużo pracy, by wszystko mu teraz odebrać - WRÓĆ DO GRY"
    },
    {
        id: "s35",
        text: "Korytarz kończy się kamiennym usypiskiem, zagradzającym dalszą drogę. Świst powietrza docierający znad zwaliska świadczy o tym, że jesteśmy blisko powierzchni. Przez szpary w kamieniach przebija się słabe, migające światło. Możemy spróbować odgruzować wyjście, ryzykując, że część zwaliska się na nas obsunie, lub poszukać innej drogi.",
        rule: "",
        show1: true,
        transText1: "Spróbujmy się wspiąć",
        changeTo1: 85,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Szukamy innej drogi - WRÓĆ DO GRY"
    },
    {
        id: "s36",
        text: "Przez moment czujemy się prawie jak dzieci podglądające przez dziurkę od klucza swoich rodziców. Tylko, że tu nie ma drzwi, jest za to wyrwa w ścianie i ta dwójka, przycupnięta na rusztowaniach u wejścia do dużej, podziemnej hali. Chłopak należy zapewne do rebeliantów. Rumieni się jak burak, ilekroć spogląda na wychudzoną twarz siedzącej obok dziewczyny. \"Ja ci chciałem to powiedzieć, bo jak dziś wyjdę, to może nie być szansy. Mi to już jedno. Mogę nie wrócić, byle tamtym się dostało\" - wyznaje rwącym głosem. Dziewczyna spogląda na niego wyczekująco, pozwalając mu się objąć. \"Bo ja... Od tamtego razu, gdy myśmy im stawili opór, to ja myślę o tobie, wiesz...\" - Dziewczyna przerywa mu i składa łagodny pocałunek na jego ustach. \"Nie daj się zabić, Dario. Będę czekała\" - mówi cicho, obdarzając go smutnym uśmiechem. Udając, że nie widzimy tej dwójki, ruszamy przez halę.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s37",
        text: "Obżarstwo na wojnie bywa równie zgubne, co głód. Mężczyzna, którego mamy przed sobą, zastygł przy samym wyjściu z kolektora z wyrazem niemego zdumienia na twarzy, tak jakby do końca nie mógł uwierzyć w swój żałosny los. Pucułowaty na twarzy, potężnej postury, odziany w drogi garnitur, próbował do samego końca walczyć o życia. Był zapewne przedsiębiorcą lub biznesmenem. Uparcie wierzył, że z pomocą łapówek uda mu się uciec z miasta. Jednak źle wyliczył cenę za swoją ucieczkę, a kiedy utknął w tunelu, nikt nie pośpieszył mu na ratunek. Nie miał przy sobie zbyt wiele. Widocznie nie jesteśmy pierwszymi, którzy trafili na tego nieszczęśnika.",
        rule: "Dodaj 1 Część Elektryczną i 3 Papierosy do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s38",
        text: "Zaglądamy do niewielkiego pomieszczenia i szybko wycofujemy się o kilka kroków, próbując wyrzucić z pamięci przerażający widok. Dziesiątki ciał, wychudzonych, sinych, bezładnie rzuconych jedno na drugie jak sterta odpadków. W sklepieniu pomieszczenia widać zamknięty właz. Tamtędy pewnie zrzucano ciała. Kolejny masowy grób, kolejny dowód bezmyślnej eksterminacji ludzkiego życia...",
        rule: "Rzuć Czarną Kością i porównaj wynik z Empatią każdej z obecnych tu Postaci. Przy wyniku równym lub niższym = podnieś Depresję danej Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s39",
        text: "Smród, wilgoć, ciasnota. Trzeba tu iść w przygarbionej pozycji, prawie na czworakach. Już po kilku minutach bolą plecy, co pogłębia jeszcze ciężar niesionych plecaków. Na nos musimy naciągnąć szmaty, smród sprawia, że kręci nam się w głowach. Każdy krok to plusk, bo brodzimy po kostki w mętnej, cuchnącej brei: plusk, plusk, plusk. Wtem czyjś but zagłębia się w coś miękkiego, nie słychać plusku. Światło latarki pozwala odkryć makabryczne znalezisko - rozkładające się zwłoki kobiety. Trzeba je minąć, ocierając się o mokrą ścianę. I iść dalej, by tu nie utknąć, jak ta biedaczka. W kieszeni ląduje znaleziony przy niej scyzoryk.",
        rule: "Dodaj 1 Nóż do Stosu Znalezisk",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s40",
        text: "Próbowali uciec - domyślamy się po zamarłych na wieczność przerażonych twarzach. Chłopak i dziewczyna, tak jak my, musieli zgubić drogę w kanałach. Zamiast do upragnionego wyjścia dotarli do kraty wychodzącej na ciemną rzekę. Oboje wyglądają, jakby zasnęli przytuleni twarzą do stalowych prętów. Domyślamy się, że zmarli z głodu lub z wycieńczenia. Dziewczyna była ranna. Pielęgniarski uniform pokrywa zakrzepła krew. Obandażowana dłoń mężczyzny opiera się na jej barku. Cuchnie zgnielizną. Kto tu kogo próbował uratować? Echa wystrzałów dobiegające z wnętrza kanałów wyrywają nas z chwilowej zadumy. W tych tunelach nie jest bezpiecznie. W tych tunelach czai się śmierć. Tylko śmierć...",
        rule: "Wybierz 1 z obecnych tu Postaci. Zapisz \"Lęk, s40\" na Pustym żetonie i połóż go na karcie tej Postaci. Od teraz aż do końca Kampanii, za każdym razem gdy ta Postać weźmie udział w Eksploracji Kanałów, podnieś jej Depresję o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s41",
        text: "Porzucony przy wąskim przejściu plecak pełen jest notatek i szkiców. Jest w nim coś jeszcze - mocno zniszczona, cle chyba wciąż sprawna kamera. Wsuwamy do niej kasetę i sprawdzamy ostatnie magranie. Drżący obraz przedstawia tłum uchodźców zmierzających ku posterunkom kontrolnym. Wezbrana fala ludzi napiera na strażników i rozstawione po obu stronach barierki. W tle słychać strzały, a gdzieś blisko płacz. Kolejne ujęcie - baraki. Wszędzie powiewają flagi tych zza rzeki. Trwa musztra. Cięcie. Młodzi mężczyźni opowiadają o patriotyzmie. Chwalą się, co zrobili kobietom z wioski. Nie da się tego słuchać. Cięcie. Znajome, ciemne kanały, sylwetki ludzi. Operator ma się pośpieszyć, inaczej zostanie z tyłu. Cięcie. Ostatnie ujęcie - blada twarz, jakieś niewyraźne słowa. Poraniona dłoń, która wyłącza kamerę.",
        rule: "Dodaj 2 Części Elektryczne do Stosu Znalezisk",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s42",
        text: "Chłopak uczepił się kraty blokującej przejście na drugą stronę tunelu i za nic nie chce nas puścić. Błędnym wzrokiem wpatruje się w skapujące ze ścian kropelki wody i czarną pieczarę, w której zniknęli przedtem jego towarzysze. \"Ja widziałem, mówię wam, gdzieś jest wyrwa w tych kratach, tam, tam... na drugą stronę. Ja zostałem z tyłu i dlatego mnie to spotkało... Czemu nie zaczekaliście pięć minut?\" - rzuca w naszą stronę z oskarżycielskim tonem, wyciągając przed siebie chudy palec. Chyba bierze nas za swoich towarzyszy. Cofamy się w obawie przed atakiem szaleńca. Nic takiego nie ma jednak miejsca. Chłopak przygląda się nam, jakby z wahaniem, po czym odwraca głowę i znowu chwyta za kratę. \"Pięć minut, tylko pięć minut\" - słyszymy za sobą echo jego głosu.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s43",
        text: "Tak musi pachnieć w piekle. Przewiązujemy usta i nos kawałkami szmat. Niewiele do daje. Zapach nieczystości jest tak intensywny, że z każdym krokiem żołądek coraz silniej protestuje. Stajemy w ścieku i z trudnością próbujemy złapać oddech. Rozglądamy się. Nie my pierwsi próbujemy tędy przejść. Przy ścianie siedzi martwa postać, opatulona szmatami. Z daleka przypomina mumię. Musiała próbować przeprawy w ten sam sposób, co my. Dalsza wędrówka tym tunelem równa się samobójstwu. Tym razem musimy zawrócić do domu. Może innym razem, gdy wybierzemy inną drogę, zajdziemy dalej.",
        rule: "Przerwij Eksplorację Kanałów. Podnieś Chorobę dowolnej z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s44",
        text: "Czy to może być... radio? Biały szum wybija się ponad odgłos płynącej w kanałach wody i z każdym kolejnym krokiem staje się coraz lepiej słyszalny. Zachowujemy ostrożność, nie wiedząc, kto o zdrowych zmysłach próbowałby łapać sygnał w podziemiach. Nikt z żywych, jak się okazuje. Gdy wchodzimy do niewielkiego pomieszczenia, spod ciała chłopca wybiega cały tabun szczurów. Jego martwa dłoń w beznadziejnym geście obejmuje pokrętło radia. W błękitnych jak u lalki oczach wciąż widać strach. Zmarł niedawno, być może z głodu. Co robił w ostatnich chwilach? Czy w akcie desperacji próbował wykorzystać szum z radia, aby odstraszyć szczury? A może miał nadzieję, że z jego pomocą zwabi do swojej kryjówki kogoś, kto go ocali? Jeśli to mieliśmy być my, spóźniliśmy się o co najmniej kilka godzin. Zamykamy chłopakowi oczy i zabieramy z jego rąk radio. Tam, dokąd odszedł, raczej nie będzie go potrzebował.",
        rule: "Jeśli w Schronieniu nie ma Radia, znajdź kartę Radia w talii Sprzętów i dodaj ją do Stosu Znalezisk. Po powrocie do domu połóż ją za darmo na dowolnym pustym polu Schronienia. Jeśli w Schronieniu jest już Radio, dodaj 2 Części Elektryczne do Stosu Znalezisk.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s45",
        text: "Instynktownie schylamy głowy, kiedy słyszymy nad sobą głośne echa wybuchów. Ataki na dzielnicę przemysłową trwają od tygodnia, ale dziź wydają się szczególnie agresywne. Jeśli ktokolwiek był teraz tam, nad nami, już po nim. Spluwamy w stronę prowizorycznej bariery wzniesionej z kawałków mebli. Walki musiały dotrzeć aż tutaj. Zapewne w ten sposób uchodźcy do niedawna próbowali się bronić. Co i rusz potykamy się o świeże ciała lub porzucony w pośpiechu dobytek. Jest tego całe mnóstwo. Mordercy zza rzeki tutaj nie próźnowali, a ich oddziały dalej mogą przeczesywać kanały. Z drugiej strony to pobojowisko może być warte ryzyka...",
        rule: "",
        show1: true,
        transText1: "Przeszukajmy to miejsce",
        changeTo1: 89,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zawracamy, póki czas. Niedawno mijaliśmy inny korytarz, lepiej sprawdzić tamtą drogę... - WRÓĆ DO GRY"
    },
    {
        id: "s46",
        text: "Niedawne opady sprawiły, że poziom wody w niektórych tunelach jest zbyt wysoki i skutecznie uniemożliwia nam przejście. Trzymamy się szerszych tuneli, z niepokojem wsłuchując się w odległy szum. Jesteśmy gdzieś w pobliżu rzeki. Z rur nad naszymi głowami skapują pojedyncze krople. Przejście przed nami blokuje wysoka krata - znów trzeba szukać innej drogi. Schodzimy niżej. Rwący ściek płynie wartkim nurtem i spływa grubą rurą prosto do rzeki. Wygląda na to, że to jedyna droga na zewnątrz.",
        rule: "",
        show1: true,
        transText1: "Zaryzykujmy spływ wraz z nieczystościami",
        changeTo1: 74,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Skok do rzeki byłby szaleństwem, lepiej wracajmy - PRZERWIJ EKSPLORAJCĘ KANAŁÓW I WRÓĆ DO GRY"
    },
    {
        id: "s47",
        text: "Trasa, którą obraliśmy, musi być często używana. Na co trudniejszych fragmentach znajdują się grube liny zabezpieczające przed upadkiem. Przy spływie ścieku znajduje się prowizoryczny posterunek rebeliantów. Jasny snop światła z latarki nagle nas oślepia. \"Kto tam?\" - chłopak, który zadaje pytanie, ma na sobie zbyt duży wojskowy mundur. Spogląda na nas nieufnie, wyciągając z ust żarzącego się papierosa. \"Tu jest strefa zamknięta. Przepustkę macie?\" - pyta agresywnym tonem. Ze spokojem próbujemy wyjaśnić, że zabłądziliśmy w kanałach. Staramy się nie wzbudzić podejrzeń, ale mamy pecha. Trafiliśmy na służbistę. Młodzik woła swoich towarzyszy i zaczyna się przesłuchanie. Trwa to długo i wcale nie rozwiewa wrodzonej nieufności chłopaka, w którego rękach spoczywa nasz los...",
        rule: "",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 82,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s48",
        text: "Martwy mężczyzna leży zawinięty w koce i wtula się policzkiem w kamienną ścianę kanału. Sądząc po mundurze, był łącznościowcem. Plecak, który przy nim znajdujemy, pełen jest paierów datowanych na okres, gdy wojna dopiero docierała do miast. Część z nich przedstawia nieaktualne mapy kanałów. Wiele kolektorów zalano, a przy reszcie można natknąć się na nieoznaczone barykady i pułapki. Mimo wszystko mapy mogą okazać się bardzo przydatne.",
        rule: "Napisz \"Wojskowa Mapa Kanałów, s48, I I\" na Pustym żetonie i połóż go na Stosie Znalezisk. Traktuj go jak szary żeton o wartości 6 i wadze 0. Podczas dowolnej Eksploracji Kanałów, zamiast dobierać kolejny kafelek Mapy Kanałów, możesz skreślić 1 kreskę z żetonu, aby natychmiast wyjść z Kanałów do dowolnego z 3 Miejsc. Gdy skreślisz ostatnią kreskę, nie możesz już więcej użyć Wojskowej Mapy Kanałów, ale żeton nadal posiada wartość 6.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s49",
        text: "Szeroki kanał przed nami wygląda jak porzucone składowisko mebli. Tapczany, ozdobne szafy, a nawet stłuczone telewizory tworzą wysoką barierę, przywodzącą na myśl surrealistyczne dzieło sztuki. Dookoła panuje cisza, nie ma śladów po jakiejkolwiek walce. Podchodzimy bliżej i nagle odskakujemy od bariery. Po drugiej stronie ktoś jest i groźnie się nam przygląda. \"Kto idzie? Podejdźcie no bliżej!\" - żąda mężczyzna zachrypnietym głosem.",
        rule: "",
        show1: true,
        transText1: "Próbujemy się wycofać",
        changeTo1: 69,
        show2: true,
        transText2: "Podchodzimy tak, jak kazał",
        changeTo2: 95,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s50",
        text: "Stracili swoją odwagę i nie mają dokąd pójść... W oddali widzimy grupkę wojskowych z niechlubnego batalionu, którzy rozsiedli się w wielkiej, podziemnej hali. W zniszczonych strojach, z opuszonymi głowami, czują się jak obcy we własnym mieście. Mieli za zadanie ochraniać lotnisko na zachodzie, ale kiedy z odległych wzgórz spadła lawina pocisków, a z nieba deszcz rakiet... opuścili stanowiska. Stchórzyli. Zapiliby się na śmierć, gdyby posiadali wystarczający zapas alkoholu. Są teraz jak duchy wałęsające się po mieście bez określonego celu. Wolimy nie mieć z nimi do czynienia. Wycofujemy się po cichu i wybieramy inną drogę.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s51",
        text: "Zapora wykonana jest z kawałków blachy owiniętych drutem i jej pokonanie wymaga sporo wysiłku. Jedno z nas rozrywa ubranie, zahaczając ramieniem o drut. Z rany leniwie kapią kropelki krwi.",
        rule: "",
        show1: true,
        transText1: "Nie mamy przy sobie Opatrunku. Lepiej wróćmy do domu i przunajmniej przemyjmy ranę",
        changeTo1: 80,
        show2: true,
        transText2: "To nic takiego, chodźmy dalej...",
        changeTo2: 64,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "Zabandażujmy i zdezynfekujmy ranę - ODRZUĆ 1 OPATRUNEK ZE STOSU ZNALEZISK I WRÓĆ DO GRY"
    },
    {
        id: "s52",
        text: "Mężczyzna podupada na duchu, gdy mówimy mu, że nikogo nie spotkaliśmy w kanałach. Wyznaje, że jego kompani wyruszyli do kanałów kilka godzin temu. To miała być krótka wyprawa. Z pomocą podkładów kolejowych mieli umocnić barykady, by utrudnić wrogowi przejście. Do tej pory nie wrócili. Żołnierz częstuje nas herbatą ze zdobionego imbryka i kawałkiem chleba, uważnie lustrując nas wzrokiem. Po kilku chwilach nasz nowy kompan otwiera butelkę wódki. Kiedy pijackim głosem zaczyna wykrzykiwać imiona zaginionych, orientujemy się, że sprawy zaszły za daleko. Zostawiamy mężczyzne samego z jego żalem. Czym prędzej znikamy w ciemności.",
        rule: "Obniż Głód 1 z obecnych tu Postaci o 1.",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s53",
        text: "Tupot naszych butów i głośne chlapnięcia, gdy trafiamy na kałuże brei. rozlegają się niczym z potężnych głośników. To wystarcza, by napastnicy rzucili się do ucieczki, nawet nie wiedząc przed kim. Gdy dobiegamy do leżącego człowieka, ten próbuje wstać. Na jego czole widać ślad po potężnym uderzeniu. Jedno oko zaczyna już puchnąć. Mimo to uśmiechamy się - nic mu nie będzie, ot, nauczka. Starszy mężczyzna nazywa się Viktor. Cóż, niech wraca z nami, przynajmniej aż do wyjścia z kanałów.",
        rule: "Do końca tej Eksploracji Kanałów Viktor jest z nami. Jeden raz podczas tej wspólnej podróży możemy zdecydować, że to właśnie na Viktora zamiast na 1 z obecnych tu Postaci spadnie efekt pechowego wydarzenia (np. Rana, Choroba, itd.).",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s54",
        text: "Błysk noża jest tak nagły, że nie zostawia nam żadnej szansy na reakcję. Napastnik przywykł do podobnych ataków. Właśnie teraz trzyma ostrze przy szyi jednego z nas. Szare długie włosy opadają na pociągłą twarz. Czarne oczy są jak dwie dopalające się bryłki węgla. \"Dawajcie, co macie, albo go zabiję\" - ostrze nacina skórę przy szyi. To nie są żarty!",
        rule: "",
        show1: true,
        transText1: "Dalej...",
        changeTo1: 81,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: ""
    },
    {
        id: "s55",
        text: "\"Cholera!\",\"A niech ich!\" - słyszymy wściekłe krzyki za sobą. Jednak żaden strzał nie padł. Może nie mieli amunicji, może bali się hałasu, jaki towarzyszyłby wystrzałom. Ważne, że nie strzelili. Tym razem mieliśmy szczęście.",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },
    {
        id: "s",
        text: "",
        rule: "",
        show1: false,
        transText1: "",
        changeTo1: 0,
        show2: false,
        transText2: "",
        changeTo2: 0,
        show3: false,
        transText3: "",
        changeTo3: 0,
        reset: "WRÓĆ DO GRY"
    },

];

// {
//     id: "s31",
//     text: "",
//     rule: "",
//     show1: false,
//     transText1: "",
//     changeTo1: 0,
//     show2: false,
//     transText2: "",
//     changeTo2: 0,
//     show3: false,
//     transText3: "",
//     changeTo3: 0,
//     reset: "WRÓĆ DO GRY"
// },
